Repository canyongbs/aidingapp, pull requests merged in 2024-08, with the labels that each got.

#197 [AIDAPP-214]: Some knowledge base items will not load after last release
  composer.lock
  database/migrations/2024_08_01_175631_data_fix_image_ids_in_tiptap_content.php
Labels: Change Type | Bug Fix

#195 [AIDAPP-104]: Receiving false notifications that the scheduler in the application is not working when it is
  _ide_helper_models.php
  app-modules/authorization/src/Models/PermissionGroup.php
  app-modules/contact/src/Models/Organization.php
  app-modules/contact/src/Models/OrganizationIndustry.php
  app-modules/contact/src/Models/OrganizationType.php
  app-modules/service-management/src/Models/ServiceRequestFeedback.php
  app/Console/Kernel.php
  app/Models/Tag.php
  app/Providers/HealthServiceProvider.php
  composer.json
  composer.lock
  resources/views/vendor/filament-spatie-health/pages/health-check-results.blade.php
Labels: Change Type | Bug Fix

#198 [AIDAPP-210]: Generating a version tag for assets is failing
  docker/s6-overlay/scripts/laravel-octane
Labels: Change Type | Bug Fix

#199 [AIDAPP-214]: Some knowledge base items will not load after last release
  database/migrations/2024_08_01_175631_data_fix_image_ids_in_tiptap_content.php
Labels: Change Type | Bug Fix

#200 [Hotfix] 0.21.1
  _ide_helper_models.php
  app-modules/authorization/src/Models/PermissionGroup.php
  app-modules/contact/src/Models/Organization.php
  app-modules/contact/src/Models/OrganizationIndustry.php
  app-modules/contact/src/Models/OrganizationType.php
  app-modules/service-management/src/Models/ServiceRequestFeedback.php
  app/Console/Kernel.php
  app/Models/Tag.php
  app/Providers/HealthServiceProvider.php
  composer.json
  composer.lock
  database/migrations/2024_08_01_175631_data_fix_image_ids_in_tiptap_content.php
  docker/s6-overlay/scripts/laravel-octane
  resources/views/vendor/filament-spatie-health/pages/health-check-results.blade.php
Labels: Change Type | Bug Fix

#202 [AIDAPP-212]: Correct set password email URL to update relative url to full path/absolute url
  app/Notifications/SetPasswordNotification.php
Labels: Change Type | Content or Styling Update

#196 [AIDAPP-206]: Introduce a badge that displays public or internal for a knowledge base article.
  app-modules/knowledge-base/resources/views/filament/pages/badges.blade.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
Labels: Change Type | New Feature

#204 [AIDAPP-211]: Refactor the primary url of the application portal
  app-modules/form/src/Actions/GenerateServiceRequestFeedbackFormEmbedCode.php
  app-modules/form/src/Filament/Blocks/UploadFormFieldBlock.php
  app-modules/portal/routes/api.php
  app-modules/portal/routes/web.php
  app-modules/portal/src/Actions/GeneratePortalEmbedCode.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalLogoutController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalRequestAuthenticationController.php
  app-modules/portal/src/Http/Middleware/EnsureKnowledgeManagementPortalIsEnabled.php
  app-modules/service-management/src/Http/Controllers/ServiceRequestFeedbackFormWidgetController.php
  portals/knowledge-management/src/Services/GetAppContext.js
Labels: Change Type | New Feature

#207 [AIDAPP-215]: Accessing the report library generates an exception
  app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php
Labels: Change Type | Bug Fix

#208 [AIDAPP-218] : Old flowbite svg is still referenced on Landlord page
  resources/views/landlord.blade.php
Labels: Change Type | Content or Styling Update

#210 [AIDAPP-191]: Add initial migration s6-overlay task
  app/Console/Commands/InitialMigration.php
  docker/s6-overlay/s6-rc.d/initial-migration/dependencies
  docker/s6-overlay/s6-rc.d/initial-migration/type
  docker/s6-overlay/s6-rc.d/initial-migration/up
  docker/s6-overlay/s6-rc.d/laravel-octane/dependencies
  docker/s6-overlay/scripts/initial-migration
  docker/s6-overlay/user/initial-migration
Labels: Change Type | New Feature

#213 [AIDAPP-219]: CVE-2024-39338
  package-lock.json
Labels: Change Type | Dependencies

#212 [AIDAPP-220]: Fix "fatal: No names found, cannot describe anything." during CI/CD
  .github/actions/composer-dependency-setup/action.yml
  .github/workflows/ci.yml
  app-modules/service-management/src/Models/ChangeRequest.php
  phpstan.neon.dist
  phpunit-ci.xml
Labels: Change Type | Bug Fix

#219 [AIDAPP-232]: Improve the display in the UI/UX for service request assignments
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ManageAssignments.php
Labels: Change Type | Content or Styling Update

#220 [AIDAPP-222] Attempting to search by entering in a phrase followed by the return key while in the client portal does not work as expected.
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | Bug Fix

#218 [AIDAPP-223]: When no logo is set for the client portal, it should default to the product logo, but instead it displays a broken image.
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
Labels: Change Type | Bug Fix

#217 [AIDAPP-226]: When performing a global search it sometimes generates an exception
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
Labels: Change Type | Bug Fix

#224 [AIDAPP-227]: Remove usage of translateLabel() method
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ListContacts.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ViewContact.php
  app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/EngagementResponsesRelationManager.php
  app-modules/contact/src/Filament/Resources/ContactSourceResource/Pages/CreateContactSource.php
  app-modules/contact/src/Filament/Resources/ContactSourceResource/Pages/EditContactSource.php
  app-modules/contact/src/Filament/Resources/ContactSourceResource/Pages/ViewContactSource.php
  app-modules/contact/src/Filament/Resources/ContactStatusResource/Pages/ViewContactStatus.php
  app-modules/engagement/src/Filament/Actions/EngagementCreateAction.php
  app-modules/engagement/src/Filament/Concerns/EngagementResponseInfolist.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/ViewEngagement.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/RelationManagers/EngagementDeliverablesRelationManager.php
  app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ListEngagementResponses.php
  app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ViewEngagementResponse.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseQualityResource/Pages/ViewKnowledgeBaseQuality.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseStatusResource/Pages/ViewKnowledgeBaseStatus.php
  app-modules/service-management/src/Filament/Concerns/ServiceRequestAssignmentInfolist.php
  app-modules/service-management/src/Filament/Concerns/ServiceRequestHistoryInfolist.php
  app-modules/service-management/src/Filament/Concerns/ServiceRequestUpdateInfolist.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/ViewServiceRequestStatus.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php
  app-modules/webhook/src/Filament/Resources/InboundWebhookResource/Pages/ViewInboundWebhook.php
Labels: Change Type | Content or Styling Update

#225 [AIDAPP-224]: Eliminate the display issues in all places throughout the app where the App Name is used.
  app/Multitenancy/Tasks/SwitchAppName.php
  config/multitenancy.php
Labels: Change Type | Content or Styling Update

#222 [AIDAPP-233]: Update GitHub Action step versions
  .github/workflows/ci.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/update_yearly_copyright.yml
Labels: Change Type | Dependencies

#227 [AIDAPP-242] & [AIDAPP-243] & [AIDAPP-244]: Fix portal rendering issues
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
Labels: Change Type | Bug Fix

#228 [Hotfix]: 0.25.1
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
Labels: Change Type | Bug Fix
