Repository canyongbs/aidingapp, pull requests merged in 2024-03, with the labels that each got.

#5 [AIDAPP-16]: Research and refactor functionality for Aiding App | Message Center
  .github/pull_request_template.md
  app-modules/engagement/config/permissions/web/custom.php
  app-modules/engagement/config/roles/web/message_center_management.php
  app-modules/engagement/resources/views/components/empty-state.blade.php
  app-modules/engagement/resources/views/components/filters.blade.php
  app-modules/engagement/resources/views/components/message-center-content.blade.php
  app-modules/engagement/resources/views/components/message-center-inbox.blade.php
  app-modules/engagement/resources/views/components/page-link.blade.php
  app-modules/engagement/resources/views/components/pagination.blade.php
  app-modules/engagement/resources/views/components/search.blade.php
  app-modules/engagement/resources/views/filament/pages/message-center.blade.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/portal/database/migrations/2023_08_16_025823_create_portal_settings.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/portal/src/Settings/PortalSettings.php
  config/local_development.php
Labels: Change Type | New Feature

#6 [AIDAPP-16]: Research and refactor functionality for Aiding App | Caseload Management
  README.md
  _ide_helper_models.php
  app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
  app-modules/caseload-management/composer.json
  app-modules/caseload-management/config/permissions/api/custom.php
  app-modules/caseload-management/config/permissions/web/custom.php
  app-modules/caseload-management/config/roles/api/caseload_management.php
  app-modules/caseload-management/config/roles/web/caseload_management.php
  app-modules/caseload-management/database/factories/CaseloadFactory.php
  app-modules/caseload-management/database/migrations/2023_09_19_173213_create_caseloads_table.php
  app-modules/caseload-management/database/migrations/2023_09_21_142344_create_caseload_subjects_table.php
  app-modules/caseload-management/database/seeders/.gitkeep
  app-modules/caseload-management/resources/views/filament/resources/caseloads/pages/edit-caseload.blade.php
  app-modules/caseload-management/src/Actions/TranslateCaseloadFilters.php
  app-modules/caseload-management/src/CaseloadManagementPlugin.php
  app-modules/caseload-management/src/Console/Commands/TranslateCaseload.php
  app-modules/caseload-management/src/Enums/CaseloadModel.php
  app-modules/caseload-management/src/Enums/CaseloadType.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResource.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/CreateCaseload.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/EditCaseload.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/GetCaseloadQuery.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/ListCaseloads.php
  app-modules/caseload-management/src/Importers/ContactCaseloadSubjectImporter.php
  app-modules/caseload-management/src/Importers/StudentCaseloadSubjectImporter.php
  app-modules/caseload-management/src/Models/Caseload.php
  app-modules/caseload-management/src/Models/CaseloadSubject.php
  app-modules/caseload-management/src/Observers/CaseloadObserver.php
  app-modules/caseload-management/src/Policies/CaseloadPolicy.php
  app-modules/caseload-management/src/Providers/CaseloadManagementServiceProvider.php
  app-modules/caseload-management/src/Registries/CaseloadManagementRbacRegistry.php
  app-modules/caseload-management/tests/Filament/CaseloadResource/CreateCaseloadTest.php
  app-modules/caseload-management/tests/Filament/CaseloadResource/EditCaseloadTest.php
  app-modules/caseload-management/tests/Filament/CaseloadResource/ListCaseloadsTest.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ListContacts.php
  app-modules/contact/src/Filament/Widgets/ContactStats.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
  app/Models/User.php
  composer.json
  composer.lock
Labels: Change Type | New Feature

#15 [AIDAPP-11]: Optimize presentation of Support Assistant and Contacts navigation labels
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
Labels: Change Type | Content or Styling Update

#16 [AIDAPP-13]: Refactor dashboard functionality included in Aiding App
  app-modules/contact/src/Filament/Pages/RecruitmentCrmDashboard.php
  resources/views/filament/widgets/features.blade.php
Labels: Change Type | New Feature

#17 [AIDAPP-12]: Optimize organization of navigation for service management
  app-modules/assistant/resources/views/filament/pages/support-assistant.blade.php
  app-modules/assistant/src/Filament/Pages/SupportAssistant.php
  app-modules/assistant/src/Filament/Resources/PromptResource.php
  app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/contact/src/Filament/Resources/ContactResource.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/inventory-management/src/Filament/Resources/AssetResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
  app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
  app-modules/survey/src/Filament/Resources/SurveyResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  config/auth.php
  resources/views/filament/widgets/features.blade.php
Labels: Change Type | Content or Styling Update

#23 [ADVAPP-438]: Setup Advising App remote development environment
  .env.example
  .github/workflows/ci.yml
  Dockerfile
  docker-compose.ci.yml
  docker-compose.dev.yml
  docker-compose.yml
  docs/local-setup.md
Labels: Change Type | Content or Styling Update, Change Type | DevOps

#24 [ADVAPP-438] Add more local setup details
  docs/local-setup.md
Labels: Change Type | DevOps, Change Type | Documentation

#27 [Hotfix] Delete message-center-inbox.blade.php
  app-modules/engagement/resources/views/components/message-center-inbox.blade.php
Labels: Change Type | Bug Fix
