Repository canyongbs/aidingapp, pull requests merged in 2024-07, with the labels that each got.

#158 [AIDAPP-166]: (Cleanup) Remove 2024_06_25_223932_data_soft_delete_service_request_priorties_with_a_deleted_type.php data migration
  app-modules/service-management/database/migrations/2024_06_25_223932_data_soft_delete_service_request_priorties_with_a_deleted_type.php
Labels: Change Type | Feature Cleanup

#162 [AIDAPP-142]: Update PR template to ask whether or not a Feature Flag was added in the PR
  .github/pull_request_template.md
Labels: Change Type | Documentation

#159 [AIDAPP-137]: Prevent Ticket Reopening in Aiding App
  app-modules/service-management/src/Enums/SystemServiceRequestClassification.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
  app-modules/service-management/src/Notifications/SendEducatableServiceRequestClosedNotification.php
  app-modules/service-management/src/Policies/ServiceRequestPolicy.php
  app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
Labels: Change Type | New Feature

#165 [AIDAPP-158] Implement Laravel SQS Extended
  composer.json
  composer.lock
  config/queue.php
Labels: Change Type | Bug Fix, Change Type | New Feature

#163 [AIDAPP-173]: Introduce the ability to save duration for service requests when an issue is closed
  app-modules/service-management/database/migrations/2024_07_03_170020_add_time_to_resolution_column_in_service_requests_table.php
  app-modules/service-management/database/migrations/2024_07_04_111255_time_to_resolution_feature_flag.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
  app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
  database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php
Labels: Change Type | New Feature

#166 [AIDAPP-169]: Introduce ability to filter by Organization within service requests
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
Labels: Change Type | New Feature

#170 [AIDAPP-188]: Fix bug with TTR data migration
  database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php
Labels: Change Type | Bug Fix

#171 [AIDAPP-188]: Fix diffInSeconds bug
  database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php
Labels: Change Type | Bug Fix

#172 [AIDAPP-186]: Update success message when submitting a request
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
Labels: Change Type | Content or Styling Update

#173 [AIDAPP-190] (Cleanup) Time To Resolution In Service request
  app-modules/service-management/database/migrations/2024_07_15_104411_data_purge_time_to_resolution_feature_flag.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
Labels: Change Type | Feature Cleanup

#174 [AIDAPP-178] Remove lock icon from service requests that are not in a closed state
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
Labels: Change Type | Bug Fix

#175 [AIDAPP-140]: Remediate issues related to CVE-2024-37890
  package-lock.json
  package.json
Labels: Change Type | Dependencies

#176 [AIDAPP-175] Unexpected behavior when opening a task from the notifications bar
  app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewHeaderAction.php
  app-modules/task/src/Filament/Resources/TaskResource/Pages/EditTask.php
  app-modules/task/src/Notifications/TaskAssignedToUserNotification.php
Labels: Change Type | Bug Fix

#181 [AIDAPP-193]: Error is thrown due to rr file missing when setting up the project for the first time
  docker/s6-overlay/scripts/fix-permissions
Labels: Change Type | Bug Fix

#179 [AIDAPP-172]: Introduce Service Requests report for the Report Library
  app-modules/report/composer.json
  app-modules/report/config/roles/api/.gitkeep
  app-modules/report/config/roles/web/.gitkeep
  app-modules/report/database/factories/.gitkeep
  app-modules/report/database/migrations/.gitkeep
  app-modules/report/database/seeders/.gitkeep
  app-modules/report/resources/views/filament/pages/report-refresh-widgets.blade.php
  app-modules/report/src/Filament/Pages/ServiceRequests.php
  app-modules/report/src/Filament/Widgets/ChartReportWidget.php
  app-modules/report/src/Filament/Widgets/RecentServiceRequestsTable.php
  app-modules/report/src/Filament/Widgets/RefreshWidget.php
  app-modules/report/src/Filament/Widgets/ServiceRequestStatusDistributionDonutChart.php
  app-modules/report/src/Filament/Widgets/ServiceRequestsOverTimeLineChart.php
  app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php
  app-modules/report/src/Filament/Widgets/StatsOverviewReportWidget.php
  app-modules/report/src/Filament/Widgets/TopServiceRequestTypesTable.php
  app-modules/report/src/Models/.gitkeep
  app-modules/report/src/Providers/ReportServiceProvider.php
  app-modules/report/src/Registries/ReportRbacRegistry.php
  app-modules/report/src/ReportPlugin.php
  app-modules/report/tests/.gitkeep
  app/Filament/Clusters/ReportLibrary.php
  composer.json
  composer.lock
  config/app-modules.php
Labels: Change Type | New Feature

#182 [AIDAPP-195]: Improve the label used to indicate copying or duplicating a knowledge base article
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
Labels: Change Type | Content or Styling Update

#183 [AIDAPP-196]: Improve knowledge management Save and Article Information buttons
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
Labels: Change Type | Content or Styling Update

#185 [AIDAPP-198]: Improve the label on the report grouping for the Report Library to Service Management
  app-modules/report/src/Filament/Pages/ServiceRequests.php
Labels: Change Type | Content or Styling Update

#187 [AIDAPP-199]: Improve the display of the tables in the Service Requests report in the Report Library
  app-modules/report/src/Filament/Widgets/RecentServiceRequestsTable.php
  app-modules/report/src/Filament/Widgets/TopServiceRequestTypesTable.php
Labels: Change Type | Content or Styling Update

#186 [AIDAPP-194]: Enhance the display of assets by better utilizing the screen real estate
  app-modules/inventory-management/src/Filament/Resources/AssetResource/Pages/ViewAsset.php
Labels: Change Type | Content or Styling Update

#178 [AIDAPP-179] Disable Updates and Service Request Assignments for service requests that are in a closed state to prevent modifications
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php
  app-modules/service-management/src/Policies/ServiceRequestUpdatePolicy.php
  app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
  app-modules/service-management/tests/ServiceRequestUpdate/EditServiceRequestUpdateTest.php
Labels: Change Type | New Feature

#188 [AIDAPP-197]: Improve the display of longer breadcrumb trails in knowledge management
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ViewKnowledgeBaseItem.php
  app-modules/knowledge-base/tests/KnowledgeBaseItem/ViewKnowledgeBaseItemTest.php
  app/Filament/Pages/Concerns/BreadcrumbCharacterLimit.php
Labels: Change Type | Content or Styling Update

#184 [AIDAPP-200]: Improve the display of charts in the Service Requests report in the Report Library & [AIDAPP-208]: Enhance and standardize the maximum height display for line charts in dashboards
  app-modules/report/src/Filament/Widgets/LineChartReportWidget.php
  app-modules/report/src/Filament/Widgets/ServiceRequestStatusDistributionDonutChart.php
  app-modules/report/src/Filament/Widgets/ServiceRequestsOverTimeLineChart.php
Labels: Change Type | Content or Styling Update

#189 [AIDAPP 202]: Add a Search Box across all categories and articles in the knowledge management portal to help users easily find information and improve navigation
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | New Feature

#190 [AIDAPP-201]: Improve the order of the menu items in the Report Center
  app/Filament/Clusters/ReportLibrary.php
  app/Filament/Clusters/UsageAuditing.php
  app/Filament/Pages/ProductHealth.php
Labels: Change Type | Content or Styling Update

#193 [AIDAPP-121]: Enhance copy/paste capabilities for Knowledge Base Articles and throughout the product.
  app-modules/division/src/Filament/Resources/DivisionResource/Pages/CreateDivision.php
  app-modules/division/src/Filament/Resources/DivisionResource/Pages/EditDivision.php
  app-modules/engagement/src/Actions/CreateEngagementBatch.php
  app-modules/engagement/src/Actions/GenerateEmailMarkdownContent.php
  app-modules/engagement/src/Actions/GenerateEngagementBodyContent.php
  app-modules/engagement/src/DataTransferObjects/EngagementBatchCreationData.php
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Actions/CreateOnDemandEngagement.php
  app-modules/engagement/src/Filament/Actions/EngagementCreateAction.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EngagementFileResource/Pages/ViewEngagementFile.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php
  app-modules/engagement/src/Models/EmailTemplate.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/engagement/src/Models/EngagementBatch.php
  app-modules/engagement/tests/Feature/Actions/CreateEngagementBatchTest.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
  app-modules/knowledge-base/src/Observers/KnowledgeBaseItemObserver.php
  app-modules/knowledge-base/src/Providers/KnowledgeBaseServiceProvider.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/Concerns/HasSharedFormConfiguration.php
  app/Filament/Actions/MediaAction.php
  app/Support/MediaEncoding/Concerns/ImplementsEncodedMediaProcessing.php
  app/Support/MediaEncoding/TiptapMediaEncoder.php
  composer.json
  composer.lock
  config/filament-tiptap-editor.php
  config/filesystems.php
  resources/css/filament/admin/theme.css
  resources/views/filament/infolists/components/html.blade.php
  tailwind.config.js
Labels: Change Type | New Feature

#192 [AIDAPP-205]: Introduce a badge that displays the current status (e.g., published) for a knowledge base article.
  app-modules/knowledge-base/resources/views/filament/pages/badges.blade.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
Labels: Change Type | New Feature
