Repository canyongbs/aidingapp, pull requests merged in 2024-11, with the labels that each got.

#305 [AIDAPP-304]: Update the database configuration for KB article categories to ensure all categories contain a URL slug
  app-modules/knowledge-base/database/migrations/2024_10_30_184951_data_add_remainig_slug_in_knowledge_base_categories_table.php
  app-modules/knowledge-base/database/migrations/2024_10_31_184250_update_slug_column_to_not_nullable_in_knowledge_base_categories_table.php
Labels: Change Type | New Feature

#306 [AIDAPP-331]: Change to APCu composer classmaps
  .github/actions/composer-dependency-setup/action.yml
  Dockerfile
Labels: Change Type | Dependencies, Change Type | DevOps

#308 [AIDAPP-335]: Include an Unassigned badge in the list view for service requests
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Documentation

#312 [AIDAPP-334]: Enhance the information displayed in the main service request list
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Documentation

#311 [AIDAPP-336]: Include a "Unassigned" filter (checkbox) in the list view for service requests
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
Labels: Change Type | Documentation

#313 [AIDAPP-337]: Make certain columns displayed in the service request list view able to be hidden
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Content or Styling Update

#314 [AIDAPP-340]: Fix slug data migration
  app-modules/knowledge-base/database/migrations/2024_10_30_184951_data_add_remainig_slug_in_knowledge_base_categories_table.php
Labels: Change Type | Bug Fix

#317 [AIDAPP-345] & [AIDAPP-344] & [AIDAPP-342] & [AIDAPP-349]: Resolve security issues
  composer.lock
Labels: Change Type | Dependencies

#316 [AIDAPP-348]: Feature Flag Cleanup: ServiceRequestStatusSystemProtection
  app-modules/service-management/resources/views/filament/pages/service-request-type-lock-icon.blade.php
  app-modules/service-management/src/Policies/ServiceRequestStatusPolicy.php
  app/Features/ServiceRequestStatusSystemProtection.php
  database/migrations/2024_10_07_185927_data_activate_feature_flag_service_request_status_system_protection.php
Labels: Change Type | Feature Cleanup

#319 [AIDAPP-338]: Data Migration Cleanup: aidingapp/app-modules/knowledge-base/database/migrations/2024_10_29_183334_data_add_remainig_slug_in_knowledge_base_categories_table.php
  app-modules/knowledge-base/database/migrations/2024_10_30_184951_data_add_remainig_slug_in_knowledge_base_categories_table.php
Labels: Change Type | Feature Cleanup

#320 [AIDAPP-339]: Enable users to search service requests by both ID and title from the service request list
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Bug Fix

#315 [AIDAPP-333]: Introduce the Assignment Type Individual so that all new service requests are assigned to a specific manager.
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
  app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
Labels: Change Type | New Feature

#324 [AIDAPP-281]: When attempting to set a hyperlink via the GDPR configuation the path to the link is incorrectly constructed when attempting to follow it
  composer.lock
Labels: Change Type | Bug Fix

#329 [AIDAPP-356]: Change to using first class callables
  app-modules/portal/routes/api.php
Labels: Change Type | Bug Fix

#331 [AIDAPP-361]: Format JS/Vue code and sort imports properly
  .prettierrc.json
  app-modules/assistant/resources/js/assistantCurrentResponse.js
  app-modules/in-app-communication/resources/js/TipTap/Extentions/SafeLink.js
  package-lock.json
  package.json
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/Badge.vue
  portals/knowledge-management/src/Components/FilterComponent.vue
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/Components/Pagination.vue
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/SelectServiceRequestType.vue
  portals/knowledge-management/src/Pages/ViewArticle.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
  portals/knowledge-management/src/Pages/ViewServiceRequest.vue
  portals/knowledge-management/src/Services/DetermineIfUserIsAuthenticated.js
  portals/knowledge-management/src/Stores/auth.js
  portals/knowledge-management/src/Stores/feature.js
  portals/knowledge-management/src/Stores/token.js
  portals/knowledge-management/src/formkit.config.js
  portals/knowledge-management/src/portal.js
  portals/knowledge-management/vite.config.js
  resources/js/app.js
  widgets/service-request-feedback-form/src/App.vue
  widgets/service-request-feedback-form/src/formkit.config.js
  widgets/service-request-feedback-form/src/widget.js
  widgets/service-request-feedback-form/tailwind.config.preset.js
  widgets/service-request-feedback-form/vite.config.js
  widgets/service-request-form/src/App.vue
  widgets/service-request-form/src/FormKit/Inputs/Signature.vue
  widgets/service-request-form/src/FormKit/Inputs/Upload.vue
  widgets/service-request-form/src/FormKit/wizard.js
  widgets/service-request-form/src/formkit.config.js
  widgets/service-request-form/src/widget.js
  widgets/service-request-form/tailwind.config.preset.js
  widgets/service-request-form/vite.config.js
Labels: Change Type | Content or Styling Update, Change Type | Dependencies

#335 [OLYMPUS-196]: Ensure all requests between Olympus and the other application are done over HTTPS
  app/Console/Commands/ConnectOlympus.php
Labels: Change Type | Bug Fix
