Repository canyongbs/aidingapp, pull requests merged in 2024-09, with the labels that each got.

#230 [AIDAPP-239]: Resolve the security issue tracked under CVE-2024-45048
  composer.json
  composer.lock
Labels: Change Type | Bug Fix, Deployment Steps

#229 [AIDAPP-238]: Clear out all existing invalid Feature Flags and switch any still required to new format
  app-modules/contact/database/migrations/2024_06_11_185237_data_activate_organization.php
  app-modules/contact/src/Policies/OrganizationIndustryPolicy.php
  app-modules/contact/src/Policies/OrganizationPolicy.php
  app-modules/contact/src/Policies/OrganizationTypePolicy.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItemMetadata.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
  app-modules/portal/database/migrations/2024_05_31_144403_create_feature_flag_for_portal_logo.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/GetKnowledgeManagementPortalTagsController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
  app-modules/service-management/database/migrations/2024_06_26_054554_data_activate_feature_service_feedback.php
  app-modules/service-management/database/migrations/2024_07_04_111255_time_to_resolution_feature_flag.php
  app-modules/service-management/database/migrations/2024_07_15_104411_data_purge_time_to_resolution_feature_flag.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
  app-modules/service-management/src/Http/Middleware/FeedbackManagementIsOn.php
  app-modules/service-management/src/Http/Middleware/ServiceRequestTypeFeedbackIsOn.php
  app-modules/service-management/src/Livewire/RenderServiceRequestFeedbackForm.php
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
  app/Policies/TagPolicy.php
  database/landlord/2024_04_09_155810_data_activate_setup_complete_feature.php
  database/landlord/2024_04_19_235223_data_purge_setup_complete_feature.php
  database/migrations/2024_05_10_200609_data_activate_permission_groups_feature.php
  database/migrations/2024_05_15_200657_data_activate_tags_feature_flag.php
  database/migrations/2024_06_02_012959_data_activate_portal_layout.php
  database/migrations/2024_06_03_173540_data_activate_notification_settings_from_name_column.php
  database/migrations/2024_06_03_200657_data_deactivate_portal_layout_feature_flag.php
  database/migrations/2024_06_05_151320_data_purge_permission_groups_feature_flag.php
  database/migrations/2024_06_07_122245_data_deactivate_notification_settings_from_name_column.php
  database/migrations/2024_07_16_113641_data_deactivate_time_to_resolution_feature_flag.php
  docker/s6-overlay/s6-rc.d/feature-flag-purge/dependencies
  docker/s6-overlay/s6-rc.d/feature-flag-purge/type
  docker/s6-overlay/s6-rc.d/feature-flag-purge/up
  docker/s6-overlay/scripts/feature-flag-purge
  docker/s6-overlay/user/feature-flag-purge
Labels: Change Type | Feature Cleanup

#231 [AIDAPP-246]: Modify local configuration to allow containers to reach each other via subdomain
  docker-compose.dev.yml
Labels: Change Type | DevOps

#233 [AIDAPP-240]: Resolve the security issue tracked under CVE-2024-45046 | Remove our override and update base package
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#235 [AIDAPP-248]: Enhance the footer to display better separation from the article itself
  portals/knowledge-management/src/Components/Footer.vue
Labels: Change Type | Content or Styling Update, Deployment Steps

#236 [AIDAPP-249]: Enhance the header in the support portal to better separate the article details from the article content
  portals/knowledge-management/src/Pages/ViewArticle.vue
Labels: Change Type | Content or Styling Update, Deployment Steps

#239 [AIDAPP-258]: Feature Flag cleanup: ContactGenerationEnabled
  app-modules/contact/database/migrations/2024_09_05_085357_data_activate_contact_generation_enabled_feature_flag.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/CreateOrganization.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php
  app/Enums/FeatureFlag.php
Labels: Change Type | Feature Cleanup

#240 [AIDAPP-268]: [Cleanup]: Feature Flag OrganizationDomain
  app-modules/contact/database/migrations/2024_08_23_162753_data_activate_organization_domains_feature_flag.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/CreateOrganization.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/ViewOrganization.php
  app/Enums/FeatureFlag.php
Labels: Change Type | Feature Cleanup

#241 [AIDAPP-245]: When viewing a list of articles within a category, paginate the results
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | Content or Styling Update, Change Type | New Feature

#245 [ADVAPP-855]: Composer update canyongbs/filament-tiptap-editor
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#243 [AIDAPP-261]: Enhance the display of Articles by including a count of articles in a given category
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | Content or Styling Update

#238 [AIDAPP-250]: Track portal views of articles and display them as article metadata
  app-modules/knowledge-base/database/migrations/2024_09_12_071605_add_portal_view_count_in_knowledge_base_articles_table.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  database/migrations/2024_09_12_073239_portal_view_count_feature_flag.php
  portals/knowledge-management/src/Pages/ViewArticle.vue
Labels: Change Type | New Feature, Feature Flag Added

#250 [AIDAPP-260]: Product Ping Health check is failing for all environments
  app/Providers/HealthServiceProvider.php
  docker-compose.dev.yml
Labels: Change Type | Bug Fix

#252 [AIDAPP-269]: When accessing the portal, the footer color is not consistently displayed.
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Pages/Home.vue
Labels: Change Type | Bug Fix

#255 [AIDAPP-204]: Remove chmod of non-existant rr
  Dockerfile
Labels: Change Type | DevOps

#257 [Bugfix]: Fix naming issues with service request routes
  app-modules/portal/routes/web.php
Labels: Change Type | Bug Fix

#258 [AIDAPP-288] & [AIDAPP-274] & [AIDAPP-275]: Switch to class based feature flagging
  .github/pull_request_template.md
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app/Enums/FeatureFlag.php
  app/Features/.gitkeep
  app/Providers/AppServiceProvider.php
  app/Support/AbstractFeatureFlag.php
  docs/data-migrations.md
  docs/feature-flagging.md
  portals/knowledge-management/src/Pages/ViewArticle.vue
  stubs/feature.stub
Labels: Change Type | Documentation, Change Type | New Feature, Change Type | Feature Cleanup

#256 [AIDAPP-217]: Separate Public or Internal and Copy badges on Knowledge Base Article details
  app-modules/knowledge-base/resources/views/filament/pages/badges.blade.php
Labels: Change Type | Bug Fix
