Repository canyongbs/aidingapp, pull requests merged in 2024-12, with the labels that each got.

#341 [AIDAPP-367]: Feature Flag Cleanup: LicenseManagement
  app-modules/license-management/database/migrations/2024_11_21_212345_data_activate_license_management.php
  app-modules/license-management/src/Policies/ProductLicensePolicy.php
  app-modules/license-management/src/Policies/ProductPolicy.php
  app/Features/LicenseManagement.php
Labels: Change Type | Feature Cleanup

#340 [Operational-Excellence/AIDAPP-366]: Feature Flag Cleanup: ContractManagement
  app-modules/contract-management/database/migrations/2024_11_26_170830_data_activate_contract_management_feature_flag.php
  app-modules/contract-management/src/Filament/Resources/ContractResource.php
  app-modules/contract-management/src/Filament/Resources/ContractTypeResource.php
  app/Features/ContractManagement.php
Labels: Change Type | Feature Cleanup

#342 [AIDAPP-376]: Fix issues with super admin role rename
  database/migrations/2024_12_05_000938_data_fix_super_admin_rename.php
Labels: Change Type | Bug Fix

#338 [AIDAPP-369]: Refactor the navigation experience for managing product administration
  app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-aws-ses-event-handling/tests/Feature/Filament/ManageAmazonSesSettingsTest.php
  app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
  app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php
  app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
  app-modules/webhook/src/Policies/InboundWebhookPolicy.php
  app/Filament/Clusters/GlobalSettings.php
  app/Filament/Clusters/ProductIntegrations.php
  app/Filament/Pages/AmazonS3.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Providers/Filament/AdminPanelProvider.php
  database/migrations/2024_12_03_064748_seed_permissions_remove_specific_global_settings_permissions.php
  tests/Feature/Filament/AmazonS3Test.php
Labels: Change Type | New Feature

#345 [AIDAPP-375]: Feature Flag Cleanup: SuperAdminRole
  app-modules/authorization/database/migrations/2024_12_02_151546_data_change_authorization.super_admin_to_sass_global_admin_in_roles_table.php
  app-modules/authorization/database/migrations/2024_12_04_175613_data_activate_super_admin_role_feature_flag.php.php
  app-modules/authorization/src/Models/Role.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/src/Policies/ServiceRequestPolicy.php
  app-modules/service-management/src/Rules/ManagedServiceRequestType.php
  app/Features/SuperAdminRole.php
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
  app/Jobs/CreateTenantUser.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  database/seeders/LocalDevelopmentSeeder.php
  database/seeders/NewTenantSeeder.php
  database/seeders/SampleSuperAdminUserSeeder.php
  tests/TestCase.php
Labels: Change Type | Feature Cleanup

#343 [AIDAPP-371]: Introduce the Assignment Type Workload so that all new service requests are assigned to those applicable managers with the most availability
  app-modules/service-management/src/Enums/ServiceRequestTypeAssignmentTypes.php
  app-modules/service-management/src/Models/ServiceRequest.php
  app-modules/service-management/src/Services/ServiceRequestType/WorkloadAssigner.php
  app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
Labels: Change Type | New Feature

#347 [AIDAPP-363]: Update the Aiding App logo used in the header
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
  resources/images/default-logo-dark-1733733973.svg
  resources/images/default-logo-dark.png
  resources/images/default-logo-light-1733734551.svg
  resources/images/default-logo-light.png
  resources/views/vendor/filament-panels/components/logo.blade.php
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Content or Styling Update

#348 [AIDAPP-368]: Fix navigation item order for Contract Management
  app-modules/license-management/src/Filament/Resources/ProductResource.php
  app-modules/report/src/Filament/Pages/ServiceRequests.php
  app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
Labels: Change Type | Content or Styling Update

#350 [AIDAPP-377]: Introduce the ability to store credentials for AI powered features in Global Settings > Product Integrations
  app-modules/ai/composer.json
  app-modules/ai/database/factories/.gitkeep
  app-modules/ai/database/migrations/2024_12_10_051111_create_ai_settings.php
  app-modules/ai/database/migrations/2024_12_10_162538_data_activate_feature_flag_for_ai_settings.php
  app-modules/ai/database/seeders/.gitkeep
  app-modules/ai/src/AiPlugin.php
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app-modules/ai/src/Models/.gitkeep
  app-modules/ai/src/Providers/AiServiceProvider.php
  app-modules/ai/src/Settings/AiSettings.php
  app-modules/ai/tests/.gitkeep
  app/Features/AiSettingsFeature.php
  composer.json
  composer.lock
Labels: Change Type | New Feature, Feature Flag Added

#352 [AIDAPP-359]: Change all Observers to be registered via ObservedBy rather than through registration in the Service Provider
  app-modules/alert/src/Models/Alert.php
  app-modules/alert/src/Providers/AlertServiceProvider.php
  app-modules/authorization/src/Models/License.php
  app-modules/authorization/src/Providers/AuthorizationServiceProvider.php
  app-modules/contact/src/Models/Contact.php
  app-modules/contact/src/Models/OrganizationIndustry.php
  app-modules/contact/src/Models/OrganizationType.php
  app-modules/contact/src/Providers/ContactServiceProvider.php
  app-modules/division/src/Models/Division.php
  app-modules/division/src/Providers/DivisionServiceProvider.php
  app-modules/engagement/src/Models/EmailTemplate.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/engagement/src/Models/EngagementBatch.php
  app-modules/engagement/src/Models/EngagementFileEntities.php
  app-modules/engagement/src/Models/SmsTemplate.php
  app-modules/engagement/src/Providers/EngagementServiceProvider.php
  app-modules/inventory-management/src/Models/AssetCheckIn.php
  app-modules/inventory-management/src/Models/AssetCheckOut.php
  app-modules/inventory-management/src/Models/MaintenanceActivity.php
  app-modules/inventory-management/src/Providers/InventoryManagementServiceProvider.php
  app-modules/notification/src/Models/OutboundDeliverable.php
  app-modules/notification/src/Models/Subscription.php
  app-modules/notification/src/Providers/NotificationServiceProvider.php
  app-modules/service-management/src/Models/ChangeRequest.php
  app-modules/service-management/src/Models/ServiceRequest.php
  app-modules/service-management/src/Models/ServiceRequestAssignment.php
  app-modules/service-management/src/Models/ServiceRequestHistory.php
  app-modules/service-management/src/Models/ServiceRequestType.php
  app-modules/service-management/src/Models/ServiceRequestUpdate.php
  app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
  app-modules/task/src/Models/Task.php
  app-modules/task/src/Providers/TaskServiceProvider.php
  app-modules/team/src/Models/TeamUser.php
  app-modules/team/src/Providers/TeamServiceProvider.php
Labels: Change Type | Content or Styling Update

#355 [AIDAPP-379]: Display service request status in the list view of service requests
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Documentation

#358 [AIDAPP-381]: Feature Flag Cleanup: AiSettingsFeature
  app-modules/ai/database/migrations/2024_12_10_162538_data_activate_feature_flag_for_ai_settings.php
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app/Features/AiSettingsFeature.php
Labels: Change Type | Feature Cleanup

#362 [AIDAPP-382]: Feature Flag Cleanup: KnowledgeBaseSubcategory
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/ListKnowledgeBaseCategories.php
  app/Features/KnowledgeBaseSubcategory.php
  database/migrations/2024_12_10_174023_data_activate_knowledge_base_subcategory_feature_flag.php
Labels: Change Type | Feature Cleanup

#363 [AIDAPP-387]: Limit the length of the description displayed in the service request list view table
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Content or Styling Update

#360 [AIDAPP-385]: Fix issue when attempting to create a service request through the administration interface an exception is generated
  app-modules/service-management/src/DataTransferObjects/ServiceRequestDataObject.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
Labels: Change Type | Bug Fix

#367 [AIDAPP-388]: Compile bugs thrown by out of date Node and NPM
  .nvmrc
  Dockerfile
Labels: Change Type | Bug Fix

#368 [AIDAPP-383]: Update RoadRunner Binary to v2024.3.0
  Dockerfile
Labels: Change Type | Dependencies

#369 [AIDAPP-391]: Improve the organization of Service Management settings
  app-modules/service-management/src/Filament/Resources/ChangeRequestStatusResource.php
  app-modules/service-management/src/Filament/Resources/ChangeRequestTypeResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php
  app-modules/service-management/src/Filament/Resources/SlaResource.php
Labels: Change Type | Content or Styling Update

#370 [AIDAPP-390]: Relocate Client Portal in Global Administration to Product Administration
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
Labels: Change Type | New Feature

#371 [AIDAPP-389]: Relocate third level navigation settings under Global Administration -> Global Settings to Global Administration at the second level
  app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
  app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
  app-modules/webhook/src/Filament/Resources/InboundWebhookResource.php
  app/Filament/Clusters/GlobalSettings.php
  app/Filament/Clusters/ProductIntegrations.php
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | New Feature

#365 [AIDAPP-373]: Display sub categories in the portal after navigating to the main category
  app-modules/portal/routes/web.php
  app-modules/portal/src/DataTransferObjects/KnowledgeBaseCategoryData.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
  portals/knowledge-management/src/Components/Breadcrumbs.vue
  portals/knowledge-management/src/Components/SubCategories.vue
  portals/knowledge-management/src/Pages/ViewArticle.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | New Feature

#372 [AIDAPP-392]: The Advising App logo is shown in light mode
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
  resources/images/default-logo-light-1733734551.svg
  resources/images/default-logo-light-1735308866.svg
  resources/views/vendor/filament-panels/components/logo.blade.php
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Bug Fix
