Repository canyongbs/aidingapp, pull requests merged in 2024-05, with the labels that each got.

#62 [AIDAPP-61] Default logo for image in emails is broken
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Bug Fix

#59 [AIDAPP-55] Enhance the way Change Management works
  app-modules/service-management/src/Policies/ChangeRequestPolicy.php
  app-modules/service-management/src/Policies/ChangeRequestStatusPolicy.php
  app-modules/service-management/src/Policies/ChangeRequestTypePolicy.php
  app-modules/service-management/tests/ChangeRequest/ListChangeRequestTest.php
  app-modules/service-management/tests/ChangeRequestStatus/ListChangeRequestStatusTest.php
  app-modules/service-management/tests/ChangeRequestType/ListChangeRequestTypeTest.php
  app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
  app/Enums/Feature.php
  app/Filament/Pages/ManageLicenseSettings.php
  tests/Helpers/AccessControl.php
Labels: Change Type | New Feature

#65 [AIDAPP-62] Update email copyright template
  resources/views/vendor/mail/html/message.blade.php
Labels: Change Type | Content or Styling Update

#64 [AIDAPP-56]: Enhance look and feel of knowledge portal
  .prettierrc.json
  app-modules/contact/graphql/contact.graphql
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ListContacts.php
  app-modules/contact/src/Filament/Tables/ContactsTable.php
  app-modules/contact/src/Imports/ContactImporter.php
  app-modules/contact/src/Models/Contact.php
  app-modules/form/src/Actions/ResolveSubmissionAuthorFromEmail.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalLogoutController.php
  app-modules/report/src/Filament/Exports/ContactExporter.php
  app/Actions/ResolveEducatableFromEmail.php
  composer.json
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/AppLoading.vue
  portals/knowledge-management/src/Components/Breadcrumbs.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Components/HelpCenter.vue
  portals/knowledge-management/src/Components/Loading.vue
  portals/knowledge-management/src/Components/MobileSidebar.vue
  portals/knowledge-management/src/Components/SearchLoading.vue
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Components/SidebarContent.vue
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/SelectServiceRequestType.vue
  portals/knowledge-management/src/Pages/ViewArticle.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
  resources/views/vendor/cookie-consent/dialog.blade.php
  widgets/service-request-form/src/App.vue
  widgets/service-request-form/src/FormKit/Inputs/OneTimePassword.vue
  widgets/service-request-form/src/FormKit/Inputs/Signature.vue
  widgets/service-request-form/src/FormKit/theme.js
  widgets/survey/src/App.vue
  widgets/survey/src/FormKit/Inputs/Rating.vue
  widgets/survey/src/FormKit/Inputs/Slider.vue
Labels: Change Type | Content or Styling Update, Change Type | New Feature

#67 [AIDAPP-22]: Split Knowledge Management Portal Render / Load Functionality
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/GetServiceRequestsController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
  portals/knowledge-management/src/App.vue
Labels: Change Type | New Feature

#63 [AIDAPP-54] Enhance the way Asset Management works
  app-modules/inventory-management/src/Policies/AssetLocationPolicy.php
  app-modules/inventory-management/src/Policies/AssetPolicy.php
  app-modules/inventory-management/src/Policies/AssetStatusPolicy.php
  app-modules/inventory-management/src/Policies/AssetTypePolicy.php
  app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
  app/Enums/Feature.php
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | New Feature

#71 [AIDAPP-63]: Resolve tenant resolution error throwing when app is access with unknown URL
  app/Multitenancy/Http/Middleware/NeedsTenant.php
  app/Providers/Filament/AdminPanelProvider.php
  app/Providers/Filament/LandlordPanelProvider.php
  app/Providers/RouteServiceProvider.php
  docker/s6-overlay/s6-rc.d/nginx/data/check
  resources/views/errors/404.blade.php
Labels: Change Type | Bug Fix, Change Type | DevOps

#70 [AIDAPP-64]: Unable to embed knowledge portal
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/EditServiceRequestForm.php
  app-modules/survey/src/Filament/Resources/SurveyResource/Pages/EditSurvey.php
Labels: Change Type | New Feature

#73 [AIDAPP-75]: Enhance the way Feedback Collection works in the application
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/CreateServiceRequestType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php
  app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
  app/Enums/Feature.php
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | New Feature

#72 [AIDAPP-67]: Enhance look and feel of navigation in Aiding App
  resources/css/filament/admin/theme.css
Labels: Change Type | Content or Styling Update

#80 [AIDAPP-70] & [AIDAPP-76]: Remove report and experimental reporting functionality
  .env.example
  _ide_helper_models.php
  app-modules/integration-ai/src/Client/AzureOpenAI.php
  app-modules/report/composer.json
  app-modules/report/config/roles/api/report_management.php
  app-modules/report/config/roles/web/report_management.php
  app-modules/report/database/factories/ReportFactory.php
  app-modules/report/database/migrations/2023_09_19_173213_create_reports_table.php
  app-modules/report/database/seeders/.gitkeep
  app-modules/report/resources/views/filament/pages/report-assistant.blade.php
  app-modules/report/resources/views/filament/resources/reports/pages/edit-report.blade.php
  app-modules/report/src/Client/AIReportChatClient.php
  app-modules/report/src/Enums/ReportModel.php
  app-modules/report/src/Filament/Exports/ContactExporter.php
  app-modules/report/src/Filament/Exports/UserExporter.php
  app-modules/report/src/Filament/Pages/ManageReportAssistantSettings.php
  app-modules/report/src/Filament/Pages/ReportAssistant.php
  app-modules/report/src/Filament/Resources/ReportResource.php
  app-modules/report/src/Filament/Resources/ReportResource/Pages/CreateReport.php
  app-modules/report/src/Filament/Resources/ReportResource/Pages/EditReport.php
  app-modules/report/src/Filament/Resources/ReportResource/Pages/ListReports.php
  app-modules/report/src/Models/Report.php
  app-modules/report/src/Observers/ReportObserver.php
  app-modules/report/src/Policies/ReportPolicy.php
  app-modules/report/src/Registries/ReportRbacRegistry.php
  app-modules/report/src/ReportPlugin.php
  app-modules/report/src/Settings/ReportAssistantSettings.php
  composer.json
  composer.lock
  database/migrations/2024_05_15_150241_data_remove_reports_table.php
  database/settings/2024_05_15_204137_data_remove_report_assistant_settings.php
Labels: Change Type | New Feature

#79 [AIDAPP-77]: Enhance the way Online Forms is presented in the application
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/ServiceRequestTypesController.php
  app-modules/service-management/src/Actions/ServiceRequest/CreateServiceRequestFromSubmission.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestFormSubmissionRelationManager.php
  app-modules/service-management/src/Observers/ServiceRequestFormSubmissionObserver.php
  app-modules/service-management/src/Policies/ServiceRequestFormPolicy.php
  app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
  app/Filament/Pages/ManageLicenseSettings.php
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
Labels: Change Type | Content or Styling Update, Change Type | New Feature

#82 [Hotfix] Update tag permissions for new system.
  database/migrations/2024_05_15_200655_create_tag_tables.php
  database/migrations/2024_05_15_200656_seed_permissions_for_tags.php
  database/migrations/2024_05_15_200657_data_activate_tags_feature_flag.php
  database/migrations/Concerns/CanModifyPermissions.php
Labels: Change Type | Bug Fix

#83 [AIDAPP-71]: Update landing page dashboard
  app-modules/service-management/src/Models/Scopes/ClassifiedAs.php
  app/Filament/Widgets/ListServiceRequestTableWidgets.php
  app/Filament/Widgets/ServiceRequestDonutChart.php
  app/Filament/Widgets/ServiceRequestLineChart.php
  app/Filament/Widgets/ServiceRequestWidget.php
Labels: Change Type | New Feature

#87 [AIDAPP-84]: Embed issue with navigation bar
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Pages/Home.vue
  resources/views/test-embed.blade.php
  routes/web.php
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#92 [AIDAPP-88]: Enhance the experience for all service requests
  .env.example
  app-modules/form/src/Actions/GenerateFormKitSchema.php
  app-modules/form/src/Actions/GenerateSubmissibleValidation.php
  app-modules/form/src/Filament/Blocks/SelectFormFieldBlock.php
  app-modules/form/src/Models/Submissible.php
  app-modules/knowledge-base/database/seeders/KnowledgeBaseItemSeeder.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalRequestAuthenticationController.php
  app-modules/service-management/src/Models/ServiceRequestFormStep.php
  config/local_development.php
  database/seeders/LocalDevelopmentSeeder.php
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/SelectServiceRequestType.vue
  portals/knowledge-management/src/portal.css
  widgets/service-request-form/src/FormKit/theme.js
Labels: Change Type | Content or Styling Update, Change Type | New Feature

#95 [AIDAPP-96]: Timeline is throwing an error in a service request
  app-modules/service-management/src/Models/ServiceRequestHistory.php
Labels: Change Type | Bug Fix

#96 [AIDAPP-82]: Resolve KB image issues
  app-modules/knowledge-base/src/Jobs/KnowledgeBaseItemDownloadExternalMedia.php
Labels: Change Type | Bug Fix

#97 [AIDAPP-82]: Forget the disks after setting config values
  app/Multitenancy/Tasks/SwitchS3FilesystemTask.php
  app/Multitenancy/Tasks/SwitchS3PublicFilesystemTask.php
Labels: Change Type | Bug Fix

#100 [AIDAPP-100]: Improve the display of the login prompt when a customer…
  portals/knowledge-management/src/App.vue
Labels: Change Type | Content or Styling Update
