Repository canyongbs/aidingapp, pull requests merged in 2024-04, with the labels that each got.

#30 [AIDAPP-35] & [AIDAPP-36]: Update default logo and favicon to be associated with Aiding App deployment
  public/favicon.ico
  public/images/default-favicon.png
  resources/images/default-logo-dark.png
  resources/images/default-logo-light.png
Labels: Change Type | Content or Styling Update

#31 [ADVAPP-353]: Ensure all commands return static::SUCCESS or static::FAILURE
  app-modules/authorization/src/Console/Commands/SetupPermissions.php
  app-modules/authorization/src/Console/Commands/SetupRoleGroups.php
  app-modules/authorization/src/Console/Commands/SetupRoles.php
  app-modules/authorization/src/Console/Commands/SyncRolesAndPermissions.php
  app-modules/engagement/src/Console/Commands/DeliverEngagements.php
  app-modules/notification/src/Console/Commands/SimulatedNotification.php
  app/Console/Commands/ClearTestMigrationCache.php
  app/Console/Commands/CreateSuperAdmin.php
  app/Console/Commands/CreateTenant.php
  app/Console/Commands/GenerateHelperFiles.php
  app/Console/Commands/GenerateLandlordApiKey.php
  app/Console/Commands/MigrateFreshLandlord.php
  app/Console/Commands/MigrateLandlord.php
  app/Console/Commands/OpenSearchDeleteAllIndices.php
  app/Console/Commands/OpenSearchList.php
  app/Console/Commands/PrintApiSchema.php
  app/Console/Commands/ValidateGraphQL.php
Labels: Change Type | Bug Fix

#32 [AIDAPP-41]: Enhance navigation look and feel in Aiding App
  composer.lock
Labels: Change Type | Bug Fix, Change Type | Dependencies

#33 AIDAPP-3: Update readme file for the project
  README.md
Labels: Change Type | Documentation

#34 [AIDAPP-42]: Reorder main navigation
  app-modules/assistant/src/Filament/Pages/SupportAssistant.php
  app-modules/contact/src/Filament/Resources/ContactResource.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/inventory-management/src/Filament/Resources/AssetResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | Content or Styling Update

#40 Hotfix/make faker dep
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#41 [Hotfix] 0.4.1
  app-modules/consent/database/seeders/ConsentAgreementSeeder.php
  app-modules/division/database/factories/DivisionFactory.php
  app-modules/knowledge-base/database/seeders/KnowledgeBaseCategorySeeder.php
  app-modules/service-management/database/seeders/ServiceRequestTypeSeeder.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#35 [AIDAPP-39]: Enhance Presentation of License Management
  app-modules/authorization/src/Enums/LicenseType.php
Labels: Change Type | Content or Styling Update

#46 [AIDAPP-37]: Remove any details on one time operations and set up new migration paradigm
  docs/data-migrations.md
Labels: Change Type | DevOps

#45 [ADVAPP-504]: Fix navigation auto-scroll when sub navigation present
  composer.lock
Labels: Change Type | Bug Fix

#47 [AIDAPP-48] Enhance create contact record experience
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/CreateContact.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/EditContact.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ViewContact.php
Labels: Change Type | Content or Styling Update

#39 [Chore] Check environment when syncing roles and permissions
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/CreatePromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/EditPromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/ListPromptsTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/ViewPromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/CreatePromptTypeTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/EditPromptTypeTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/ListPromptTypesTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/ViewPromptTypeTest.php
  app-modules/authorization/src/Console/Commands/SyncRolesAndPermissions.php
  tests/Pest.php
Labels: Change Type | DevOps

#51 [AIDAPP-50] Enhance the labels used for Service Requests
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
  app-modules/service-management/tests/ServiceRequest/ViewServiceRequestTest.php
Labels: Change Type | Content or Styling Update

#52 [AIDAPP-53] Updated and enhanced default knowledge base categories
  app-modules/knowledge-base/database/seeders/KnowledgeBaseCategorySeeder.php
Labels: Change Type | Content or Styling Update

#53 [AIDAPP-52] Updated and enhanced default Types
  app-modules/service-management/database/seeders/ServiceRequestTypeSeeder.php
Labels: Change Type | Content or Styling Update

#54 [AIDAPP-51] Update default statuses
  app-modules/service-management/database/seeders/ServiceRequestStatusSeeder.php
  app-modules/service-management/src/Enums/SystemServiceRequestClassification.php
Labels: Change Type | Content or Styling Update

#60 [ADVAPP-508]: Session Driver inconsistencies
  config/database.php
Labels: Change Type | Bug Fix

#61 [AIDAPP-58] Unable to search service requests
  app-modules/service-management/database/migrations/2023_08_11_235451_create_implicit_varchar_as_uuid_cast.php
Labels: Change Type | Bug Fix
