Repository canyongbs/aidingapp, pull requests merged in 2024-06, with the labels that each got.

#104 [AIDAPP-109]: Fix display issue for cookies banner
  resources/views/vendor/cookie-consent/dialog.blade.php
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#109 [AIDAPP-115]: Setting division when creating a knowledge article produces an error
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItemMetadata.php
Labels: Change Type | Bug Fix

#117 [AIDAPP-123]: Better match the path the check for file existence
  app/Support/MediaEncoding/TiptapMediaEncoder.php
Labels: Change Type | Bug Fix

#113 [AIDAPP-111]: Introduce Report Library coming soon page under Reporting
  app/Filament/Pages/ReportLibrary.php
  database/migrations/2024_06_07_094732_seed_permissions_add_report_library.php
Labels: Change Type | New Feature

#114 [AIDAPP-119]: Update labels in global settings for Portals and Knowledge Portal
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
Labels: Change Type | Content or Styling Update

#120 [AIDAPP-118]: Remove the left hand navigation panel from the Knowledge Portal
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/Components/MobileSidebar.vue
  portals/knowledge-management/src/Components/SidebarContent.vue
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/SelectServiceRequestType.vue
  portals/knowledge-management/src/Pages/ViewArticle.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | New Feature

#124 [AIDAPP-117]: Introduce Canyon GBS copyright at bottom of knowledge portal
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/Footer.vue
Labels: Change Type | Content or Styling Update

#125 [AIDAPP-122]: Fix DeliveryEngagements Job
  app-modules/engagement/src/Actions/DeliverEngagements.php
Labels: Change Type | Bug Fix

#108 [AIDAPP-107]: (Cleanup) Introduce configurable layout options for the KB portal
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  database/migrations/2024_06_03_200657_data_deactivate_portal_layout_feature_flag.php
Labels: Change Type | Feature Cleanup

#123 [AIDAPP-113] - Ensure Tenant settings are editable by Super Admins
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-aws-ses-event-handling/tests/Feature/Filament/ManageAmazonSesSettingsTest.php
  app/Filament/Pages/AmazonS3.php
  database/migrations/2024_06_10_132513_seed_permissons_add_manage_s3_settings.php
  resources/views/filament/pages/amazon-s3.blade.php
  tests/Feature/Filament/AmazonS3Test.php
Labels: Change Type | New Feature

#129 [AIDAPP-124]: Populate Tenant ID and User ID into Sentry reports
  app/Listeners/ClearSentryUser.php
  app/Listeners/SetSentryUser.php
  app/Multitenancy/Listeners/RemoveSentryTenantTag.php
  app/Multitenancy/Listeners/SetSentryTenantTag.php
  app/Providers/AppServiceProvider.php
  app/Providers/EventServiceProvider.php
  config/octane.php
Labels: Change Type | New Feature

#127 [AIDAPP-86]: Copy over permission migration creation details from ADVAPP
  app/Console/Commands/CreatePermissionMigration.php
  app/Overrides/Laravel/PermissionMigrationCreator.php
  app/Providers/AppServiceProvider.php
  database/migrations/Concerns/CanModifyPermissions.php
  docs/data-migrations.md
  docs/roles-and-permissions.md
  stubs/permission-migration.stub
Labels: Change Type | Documentation, Change Type | New Feature

#131 [AIDAPP-126]: Improve the boxed portal view to be more prominent
  portals/knowledge-management/src/App.vue
Labels: Change Type | Content or Styling Update

#132 [AIDAPP- 127] - Address scaling to mobile view for the logo scaling
  portals/knowledge-management/src/Components/Header.vue
Labels: Change Type | Bug Fix

#136 [AIDAPP-128]: Improve the portal display background and sign in button
  portals/knowledge-management/src/Components/Header.vue
Labels: Change Type | Bug Fix

#138 [AIDAPP-138]: Fix issues with JS dependencies not being available for container start processes
  package-lock.json
  package.json
Labels: Change Type | Bug Fix

#139 [AIDAPP-135]: Add tag for dependencies to avoid caching of assets as they change from release to release
  app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
  app-modules/portal/src/Actions/GeneratePortalEmbedCode.php
  app/Providers/AppServiceProvider.php
Labels: Change Type | Bug Fix

#141 [Hotfix]: 0.15.2
  app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
  app-modules/portal/src/Actions/GeneratePortalEmbedCode.php
  app/Providers/AppServiceProvider.php
Labels: Change Type | Bug Fix

#142 [AIDAPP-143]: Prevent Engagements from putting jobs onto the email queue if it's on the queue but hasn't been processed
  app-modules/engagement/src/Actions/EngagementEmailChannelDelivery.php
  app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
Labels: Change Type | Bug Fix

#143 [AIDAPP-147]: Reduce confusion around accessing KB article properties
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
Labels: Change Type | Content or Styling Update

#144 [AIDAPP-136] Remove OrganizationType and OrganizationIndustry data migration
  database/migrations/2024_06_13_100154_data_seed_data_in_organization_types_table.php
  database/migrations/2024_06_13_100226_data_seed_data_in_organization_industries_table.php
Labels: Change Type | New Feature

#145 [AIDAPP-153] Rename Knowledge Base to Knowledge Management in the main navigation
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
Labels: Change Type | Content or Styling Update

#150 [AIDAPP-157]: Creation of AidingApp Tenant Failed
  app/Http/Requests/Tenants/CreateTenantRequest.php
Labels: Change Type | Bug Fix

#146 [AIDAPP-154]: Improve error message text for issues experienced by customers
  resources/svg/canyongbs-500.svg
  resources/svg/flowbite-500.svg
  resources/views/errors/500.blade.php
Labels: Change Type | Content or Styling Update

#148 [AIDAPP-152]: Reorganize the primary navigation user experience
  app-modules/contact/src/Filament/Resources/ContactResource.php
  app-modules/contact/src/Filament/Resources/OrganizationResource.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/inventory-management/src/Filament/Resources/AssetResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
  app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Filament/Clusters/UsageAuditing.php
  app/Filament/Pages/ProductHealth.php
  app/Filament/Pages/ReportLibrary.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#152 [AIDAPP-125]: Introduce ability to duplicate knowledge base articles
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
  app/Support/MediaEncoding/TiptapMediaEncoder.php
Labels: Change Type | New Feature

#154 [AIDAPP-149]: Enhance Client Portal UI settings for Logo and Favicon
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
Labels: Change Type | Content or Styling Update

#151 [AIDAPP-155]: Investigate and resolve cause of error related to service management issue
  app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php
  app-modules/service-management/database/migrations/2024_06_25_223932_data_soft_delete_service_request_priorties_with_a_deleted_type.php
  app-modules/service-management/src/Observers/ServiceRequestTypeObserver.php
  app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
  app-modules/service-management/tests/ServiceRequestType/ServiceRequestTypeObserverTest.php
Labels: Change Type | Bug Fix, Change Type | New Feature

#155 [AIDAPP-150]: Setting a favicon or logo should not be possible when KB is disabled
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
Labels: Change Type | Content or Styling Update

#156 [AIDAPP-168]: The health check page is throwing 500s randomly when viewed in Dev and Prod
  resources/views/vendor/filament-spatie-health/pages/health-check-results.blade.php
Labels: Change Type | Bug Fix

#157 [AIDAPP-171]: Update all docs to instruct users to update to the most recent version of Docker
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  docs/local-setup.md
Labels: Change Type | DevOps, Change Type | Documentation
