Repository canyongbs/aidingapp, pull requests merged in 2024-10, with the labels that each got.

#263 [Bugfix]: Remove reference to old FeatureFlag ENUM
  resources/views/vendor/cookie-consent/dialog.blade.php
Labels: Change Type | Bug Fix

#259 [AIDAPP-285]: After a contact authenticates in the portal, a list of service requests assigned to a contact are not showing up
  portals/knowledge-management/src/App.vue
Labels: Change Type | Bug Fix

#264 [AIDAPP-293]: Resolve issues in our Docker Compose setup from Docker Updates
  docker-compose.yml
Labels: Change Type | Bug Fix

#249 [AIDAPP-263]: Enhance the portal header by including the ability to search no matter what page of the portal the user is on
  portals/knowledge-management/src/Components/GlobalSearchBar.vue
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Stores/globalState.js
Labels: Change Type | New Feature

#266 [AIDAPP-288]: Fix path in FeatureFlag stub
  stubs/feature.stub
Labels: Change Type | Bug Fix

#267 [AIDAPP-294]: Feature Flag Cleanup: ServiceRequestTypeManagerAuditor
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ManageServiceRequestTypeAuditors.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ManageServiceRequestTypeManagers.php
  app/Features/ServiceRequestTypeManagerAuditor.php
  database/migrations/2024_10_01_192905_data_activate_service_request_type_manager_auditor.php
Labels: Change Type | Feature Cleanup

#268 [AIDAPP-299]: When viewing the GDPR banner, the message is presented outside of the intended CSS container
  resources/views/vendor/cookie-consent/dialog.blade.php
Labels: Change Type | Content or Styling Update

#271 [AIDAPP-295]: Set "secure" to true by default in session config
  config/session.php
Labels: Change Type | New Feature

#280 [AIDAPP-310]: Enhance the description of Knowledge Management by renaming this function to the more common language in ITSM
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
  app/Filament/Clusters/KnowledgeManagement.php
Labels: Change Type | Content or Styling Update

#277 [AIDAPP-301] Prevent users from viewing service requests of types that they are not managers or auditors of
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/src/Policies/ServiceRequestPolicy.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
  app-modules/service-management/tests/ServiceRequest/ViewServiceRequestTest.php
Labels: Change Type | New Feature

#283 [AIDAPP-305]: In the article view page, modify the pagination approach to improve the display of articles
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
Labels: Change Type | Content or Styling Update

#284 [AIDAPP-312]: Introduce notification preferences for service request types
  app-modules/service-management/database/migrations/2024_10_16_161945_add_notification_columns_in_service_request_types_table.php
  app-modules/service-management/database/migrations/2024_10_16_162458_data_activate_feature_flag_service_request_types_notification.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
  app-modules/service-management/src/Models/ServiceRequestType.php
  app/Features/ServiceRequestTypeNotifications.php
  composer.lock
Labels: Change Type | New Feature, Feature Flag Added

#282 [AIDAPP-309]: After changing an article from public to internal, the article is still available via the link on the portal
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  portals/knowledge-management/src/Pages/ViewArticle.vue
Labels: Change Type | Bug Fix

#286 [AIDAPP-321]: Portal search loads forever and throws an error
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
Labels: Change Type | Bug Fix

#287 [AIDAPP-313]: Adjust composer.json configuration and optimizations for performance benefits in Production and reduced complexity in development
  .github/actions/composer-dependency-setup/action.yml
  Dockerfile
  _ide_helper_models.php
  app-modules/assistant/composer.json
  app-modules/audit/config/audit.php
  app-modules/authorization/config/permission.php
  app-modules/consent/composer.json
  app-modules/contact/composer.json
  app-modules/contact/src/Rules/UniqueOrganizationDomain.php
  app-modules/division/composer.json
  app-modules/engagement/tests/EngagementFile/EngagementFilePruningTest.php
  app-modules/form/composer.json
  app-modules/in-app-communication/composer.json
  app-modules/integration-ai/composer.json
  app-modules/integration-ai/src/Client/Playground/MockStreamResponseGenerator.php
  app-modules/integration-aws-ses-event-handling/composer.json
  app-modules/integration-google-analytics/composer.json
  app-modules/integration-google-recaptcha/composer.json
  app-modules/integration-microsoft-clarity/composer.json
  app-modules/inventory-management/composer.json
  app-modules/notification/tests/Features/NotificationSendingTest.php
  app-modules/portal/composer.json
  app-modules/report/composer.json
  app-modules/service-management/src/Http/Middleware/FeedbackManagementIsOn.php
  app-modules/service-management/src/Http/Middleware/ServiceRequestTypeFeedbackIsOn.php
  app-modules/team/composer.json
  app-modules/timeline/composer.json
  app/View/Components/DatePicker.php
  app/View/Components/Dropzone.php
  app/View/Components/SelectList.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/app.php
  config/auth.php
  config/data.php
  config/filament-tiptap-editor.php
  config/lara-asp-graphql.php
  config/lighthouse.php
  config/media-library.php
  config/sanctum.php
  config/settings.php
  php-cs-fixer.php
  stubs/app-modules/composer-stub.json
  tests/Pest.php
  tests/Unit/LicenseSettingsEmailQuotaTracking.php
  tests/Unit/LicenseSettingsSmsQuotaTracking.php
Labels: Change Type | Content or Styling Update, Change Type | Dependencies, Change Type | DevOps

#289 [AIDAPP-314]: Feature Flag cleanup: KnowledgeBaseCategorySlug
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/CreateKnowledgeBaseCategory.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/EditKnowledgeBaseCategory.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/ViewKnowledgeBaseCategory.php
  app/Features/KnowledgeBaseCategorySlug.php
  database/migrations/2024_10_10_142117_data_activate_feature_flag_knowledge_base_category_slug.php
Labels: Change Type | Feature Cleanup

#291 [AIDAPP-318]: Feature Flag Cleanup: FeaturedArticle
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItemMetadata.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
  app/Features/FeaturedArticle.php
  database/migrations/2024_10_14_102853_data_activate_featured_flag_featured_article.php
Labels: Change Type | Feature Cleanup

#294 [AIDAPP-325]: Fix Filament Form Header H3 to actually return an actual h3 element
  resources/views/filament/forms/components/heading-three.blade.php
Labels: Change Type | Bug Fix

#292 [AIDAPP-319]: Feature Flag Cleanup: ServiceRequestTypeNotifications
  app-modules/service-management/database/migrations/2024_10_16_162458_data_activate_feature_flag_service_request_types_notification.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
  app/Features/ServiceRequestTypeNotifications.php
Labels: Change Type | Feature Cleanup

#295 [AIDAPP-326]: Fix Filament Form Paragraph component to actually return a p tag
  resources/views/filament/forms/components/paragraph.blade.php
Labels: Change Type | Bug Fix

#293 [AIDAPP-315]: Update the Canyon GBS logo for Aiding App
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
  app-modules/service-management/src/Http/Controllers/ServiceRequestFeedbackFormWidgetController.php
  portals/knowledge-management/src/Components/Footer.vue
  resources/images/canyon-logo-dark.png
  resources/images/canyon-logo-light.png
  resources/svg/CGBS_Logo_FullColor_Dark.svg
  resources/svg/CGBS_Logo_FullColor_Light.svg
  resources/views/filament/footer.blade.php
Labels: Change Type | Content or Styling Update

#288 [AIDAPP-317]: Feature Flag cleanup: ServiceRequestTypeAssignments
  app-modules/service-management/database/migrations/2024_10_11_163839_data_activate_feature_flag_service_request_types_assignments.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeAssignments.php
  app/Features/ServiceRequestTypeAssignments.php
Labels: Change Type | Feature Cleanup

#298 [AIDAPP-332]: Unable to thumb up or thumb down an article
  .env.example
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/StoreKnowledgeBaseArticleVoteController.php
  app/Multitenancy/Tasks/SwitchSessionDriver.php
Labels: Change Type | Bug Fix

#290 [AIDAPP-306]: Introduce search result pagination when using the client portal
  app-modules/portal/src/DataTransferObjects/KnowledgeManagementSearchData.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
  portals/knowledge-management/src/Components/Pagination.vue
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | New Feature

#299 [Hotfix]: 0.33.1
  .env.example
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/StoreKnowledgeBaseArticleVoteController.php
  app/Multitenancy/Tasks/SwitchSessionDriver.php
Labels: Change Type | Bug Fix

#296 [AIDAPP-308]: In the portal, when there are votes on an article, indicate what percentage of users found the article helpful.
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/StoreKnowledgeBaseArticleVoteController.php
  portals/knowledge-management/src/Pages/ViewArticle.vue
Labels: Change Type | New Feature

#300 [AIDAPP-330]: Update the copyright text for the footer in Aiding App
  portals/knowledge-management/src/Components/Footer.vue
  resources/views/filament/footer.blade.php
Labels: Change Type | Content or Styling Update

#302 [AIDAPP-323]: Enhance the display of articles by all articles, featured articles, and most viewed articles
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
  portals/knowledge-management/src/Components/FilterComponent.vue
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | New Feature

#304 [AIDAPP-324]: Update the Notifications icon in the service request types
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
Labels: Change Type | Content or Styling Update
