Repository canyongbs/aidingapp, pull requests merged in 2025-09, with the labels that each got.

#653 [AIDAPP-687]: Add a merge value across all service request templates for contact name
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
  app-modules/service-management/src/Notifications/Concerns/HandlesServiceRequestTemplateContent.php
Labels: Change Type | New Feature

#656 [AIDAPP-689]: Feature Flag Cleanup: AssignedToMergeTagRenameFeatureFlag
  app-modules/service-management/database/migrations/2025_09_01_090216_tmp_data_rename_assigned_to_merge_tag_to_assigned_staff_name_in_service_request_type_email_templates_table.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
  app-modules/service-management/src/Notifications/Concerns/HandlesServiceRequestTemplateContent.php
  app/Features/AssignedToMergeTagRenameFeatureFlag.php
Labels: Change Type | Feature Cleanup

#665 [AIDAPP-674]: Resolve the security issue tracked under CVE-2025-54801 & [AIDAPP-684]: Resolve the security issue tracked under CVE-2025-9288
  Dockerfile
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#661 [AIDAPP-694]: Some users are reporting that forms are not remaining within the bounds of the page
  portals/knowledge-management/src/Pages/CreateServiceRequest.vue
  portals/knowledge-management/src/Pages/SelectServiceRequestType.vue
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#670 Solve lint issues
  app-modules/service-management/src/Models/Sla.php
  app-modules/service-management/src/Notifications/ChangeRequestAwaitingApprovalNotification.php
  app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php
  app-modules/service-management/src/Notifications/ServiceRequestAssigned.php
  app-modules/service-management/src/Notifications/ServiceRequestClosed.php
  app/Filament/Widgets/ServiceRequestDonutChart.php
  app/Filament/Widgets/ServiceRequestLineChart.php
  app/Filament/Widgets/ServiceRequestWidget.php
  app/Models/Concerns/BelongsToEducatable.php
  database/factories/Concerns/RandomizeState.php
Labels: Change Type | Bug Fix

#679 [AIDAPP-708]: Clean up FeedbackReminderFeature
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/CreateServiceRequestType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php
  app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php
  app/Features/FeedbackReminderFeature.php
  database/migrations/2025_08_11_144015_data_activate_feedback_reminder_feature.php
Labels: Change Type | Feature Cleanup

#678 [AIDAPP-709]: Clean up ProjectManagersAuditorsFeature
  app-modules/project/database/migrations/2025_07_07_172516_data_activate_project_managers_auditors_feature_feature_flag.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageAuditors.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageManagers.php
  app-modules/project/src/Policies/ProjectPolicy.php
  app/Features/ProjectManagersAuditorsFeature.php
Labels: Change Type | Feature Cleanup

#680 [AIDAPP-707]: Clean up ConfidentialTaskFeature
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactTasks.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageTasks.php
  app-modules/task/src/Filament/Concerns/TaskEditForm.php
  app-modules/task/src/Filament/Concerns/TaskViewActionInfoList.php
  app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php
  app-modules/task/src/Models/Scopes/ConfidentialTaskScope.php
  app/Features/ConfidentialTaskFeature.php
  database/migrations/2025_07_01_173325_data_activate_task_confidential_feature_flag.php
Labels: Change Type | Feature Cleanup

#683 [AIDAPP-711]: Temporary Data Migration Cleanup: 2025_08_07_144652_tmp_seed_data_project_milestone_statuses_seeder.php
  app-modules/project/database/migrations/2025_08_07_144652_tmp_seed_data_project_milestone_statuses_seeder.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ManageMilestonesTest.php
Labels: Change Type | Feature Cleanup
