Repository canyongbs/aidingapp, pull requests merged in 2025-08, with the labels that each got.

#629 [AIDAPP-665]: Introduce the ability to see CSAT and NPS scores on a service request
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/Feedback.php
Labels: Change Type | New Feature

#634 [AIDAPP-672]: Resolve the security issue tracked under CVE-2025-27209 & [AIDAPP-673]: Resolve the security issue tracked under CVE-2025-27210
  .nvmrc
  Dockerfile
  package-lock.json
Labels: Change Type | Dependencies

#639 [AIDAPP-666]: Introduce service feedback reminder option
  app-modules/service-management/database/migrations/2025_08_11_143616_add_is_reminders_enabled_in_service_request_types_table.php
  app-modules/service-management/database/migrations/2025_08_11_143801_add_survey_and_reminder_fields_to_service_requests_table.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/CreateServiceRequestType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php
  app-modules/service-management/src/Jobs/SendClosedServiceRequestFeedbackReminders.php
  app-modules/service-management/src/Models/ServiceRequest.php
  app-modules/service-management/src/Models/ServiceRequestType.php
  app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php
  app/Console/Kernel.php
  app/Features/FeedbackReminderFeature.php
  database/migrations/2025_08_11_144015_data_activate_feedback_reminder_feature.php
Labels: Change Type | New Feature, Feature Flag Added

#641 [AIDAPP-677]: Resolve the security issue tracked under CVE-2025-47907
  package-lock.json
  package.json
Labels: Change Type | Dependencies

#640 [AIDAPP-678]: Feature Flag Cleanup: ProjectMilestoneFeature
  app-modules/project/database/migrations/2025_08_11_161301_data_activate_project_milestone_feature_flag.php
  app-modules/project/src/Filament/Resources/ProjectMilestoneStatusResource.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageMilestones.php
  app/Features/ProjectMilestoneFeature.php
Labels: Change Type | Feature Cleanup

#648 [AIDAPP-685]: Resolve the security issue tracked under CVE-2025-54370
  composer.lock
Labels: Change Type | Dependencies
