Repository canyongbs/aidingapp, pull requests merged in 2025-03, with the labels that each got.

#444 [AIDAPP-464]: Enhance the contact emails view to integrate and display both inbound and outbound email messages together
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactEngagement.php
  app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/EngagementsRelationManager.php
  app-modules/contact/src/Models/Contact.php
  app-modules/contact/tests/Contact/ListContactTest.php
  app-modules/engagement/src/Actions/RelationManagerSendEngagementAction.php
  app-modules/engagement/src/Enums/EngagementDeliveryMethod.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
  app-modules/engagement/src/Models/EngagementResponse.php
  app-modules/notification/src/Enums/NotificationChannel.php
Labels: Change Type | New Feature

#449 [AIDAPP-477]: Resolve the security issue tracked under CVE-2021-44906
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#450 [Hotfix]: 0.51.2
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#452 [AIDAPP-488]: Feature Flag Cleanup: RoundRobinId
  app-modules/service-management/database/migrations/2024_11_28_125122_data_activate_feature_flag_round_robin_id.php
  app-modules/service-management/src/Services/ServiceRequestType/RoundRobinAssigner.php
  app/Features/RoundRobinId.php
Labels: Change Type | Feature Cleanup

#448 [AIDAPP-486]: Fix outdated lock file
  composer.lock
Labels: Change Type | Dependencies

#453 [AIDAPP-489]: Feature Flag Cleanup: ServiceRequestTypeEmailTemplateFeature
  app-modules/service-management/database/migrations/2025_01_03_091338_data_activate_service_request_type_email_template_feature.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php
  app/Features/ServiceRequestTypeEmailTemplateFeature.php
Labels: Change Type | Feature Cleanup

#451 [AIDAPP-487]: Feature Flag Cleanup: IncidentUpdateFeature
  app-modules/service-management/database/migrations/2025_02_26_180821_data_activate_incident_update_feature.php
  app-modules/service-management/src/Filament/Resources/IncidentResource.php
  app-modules/service-management/src/Filament/Resources/IncidentResource/Pages/ManageIncidentUpdate.php
  app/Features/IncidentUpdateFeature.php
Labels: Change Type | Feature Cleanup

#458 [AIDAPP-496]: Resolve the security issue tracked under CVE-2025-27517
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#455 [AIDAPP-493]: Introduce the ability to store job titles and phone numbers for users
  app/Features/UserWorkFieldsFeature.php
  app/Filament/Resources/UserResource.php
  app/Models/User.php
  app/Providers/FilamentServiceProvider.php
  composer.json
  composer.lock
  database/migrations/2025_03_10_050447_add_work_number_extension_mobile_to_users_table.php
  database/migrations/2025_03_10_052618_data_activate_user_work_fields_feature.php
  public/vendor/filament-phone-input/flags.webp
  public/vendor/filament-phone-input/flags@2x.webp
  public/vendor/filament-phone-input/globe.webp
  public/vendor/filament-phone-input/globe@2x.webp
  resources/lang/en/validation.php
Labels: Change Type | New Feature, Feature Flag Added

#456 [AIDAPP-491]: Improve phone inputs for organizations
  app-modules/contact/database/factories/OrganizationFactory.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/CreateOrganization.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php
  app-modules/contact/tests/Organization/RequestFactories/EditOrganizationRequestFactory.php
Labels: Change Type | Content or Styling Update

#457 [AIDAPP-492]: Improve phone inputs for contacts
  app-modules/contact/database/factories/ContactFactory.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/CreateContact.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/EditContact.php
  app-modules/contact/tests/Contact/RequestFactories/CreateContactRequestFactory.php
  app-modules/contact/tests/Contact/RequestFactories/EditContactRequestFactory.php
Labels: Change Type | Content or Styling Update

#470 [AIDAPP-498]: Feature Flag Cleanup: UserWorkFieldsFeature
  app/Features/UserWorkFieldsFeature.php
  app/Filament/Resources/UserResource.php
  database/migrations/2025_03_10_052618_data_activate_user_work_fields_feature.php
Labels: Change Type | Feature Cleanup

#462 [AIDAPP-494]: Add a filter for service requests for the party a ticket is assigned to, including unassigned as an option
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
Labels: Change Type | New Feature

#473 [AIDAPP-514]: Fix the storage of job batches so they are properly managed within tenants
  app/Multitenancy/Tasks/SwitchTenantDatabasesTask.php
Labels: Change Type | Bug Fix

#476 [AIDAPP-515]: An error is thrown when a Contact submits a Service Request through the portal
  app-modules/contact/src/Models/Contact.php
  app/Enums/Feature.php
  app/Models/Authenticatable.php
  app/Models/SystemUser.php
  app/Providers/AuthServiceProvider.php
Labels: Change Type | Bug Fix

#472 [AIDAPP-501]: Feature Flag Cleanup: ServiceRequestStatusColorFeature
  app-modules/report/src/Filament/Widgets/ServiceRequestStatusDistributionDonutChart.php
  app-modules/service-management/database/migrations/2024_10_07_180708_data_seed_system_protected_new_status_for_service_request_statuses.php
  app-modules/service-management/database/migrations/2025_03_12_144425_data_convert_service_request_status_colors_to_literal_values.php
  app-modules/service-management/database/migrations/2025_03_12_144426_data_activate_service_request_status_colors_feature.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/CreateServiceRequestStatus.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/EditServiceRequestStatus.php
  app-modules/service-management/src/Models/ServiceRequestStatus.php
  app/Features/ServiceRequestStatusColorFeature.php
  app/Filament/Widgets/ServiceRequestDonutChart.php
Labels: Change Type | Feature Cleanup

#471 [AIDAPP-505]: When attempting to save changes after editing a user, an error message appears stating that the email address already exists
  app-modules/authorization/tests/Feature/Filament/Resources/UserResources/Pages/EditUserTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/UserResources/Pages/ListUsersTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/UserResources/Pages/ViewUserTest.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Filament/Resources/UserResource/Pages/ViewUser.php
  database/factories/UserFactory.php
Labels: Change Type | Bug Fix

#477 [Hotfix]: 0.53.2
  app-modules/contact/src/Models/Contact.php
  app-modules/report/src/Filament/Widgets/ServiceRequestStatusDistributionDonutChart.php
  app-modules/service-management/database/migrations/2024_10_07_180708_data_seed_system_protected_new_status_for_service_request_statuses.php
  app-modules/service-management/database/migrations/2025_03_12_144425_data_convert_service_request_status_colors_to_literal_values.php
  app-modules/service-management/database/migrations/2025_03_12_144426_data_activate_service_request_status_colors_feature.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/CreateServiceRequestStatus.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/EditServiceRequestStatus.php
  app-modules/service-management/src/Models/ServiceRequestStatus.php
  app/Enums/Feature.php
  app/Features/ServiceRequestStatusColorFeature.php
  app/Filament/Widgets/ServiceRequestDonutChart.php
  app/Models/Authenticatable.php
  app/Models/SystemUser.php
  app/Providers/AuthServiceProvider.php
Labels: Change Type | Bug Fix

#479 [AIDAPP-358]: Upgrade to Larastan 3.0 and PHPStan 2.0
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Change Type | Dependencies

#475 [AIDAPP-506]: Introduce the ability to attach multiple files in the ticket submission from the client portal
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
  app-modules/service-management/src/Models/MediaCollections/UploadsMediaCollection.php
  app-modules/service-management/src/Models/ServiceRequest.php
  package-lock.json
  package.json
  widgets/service-request-form/src/FormKit/Inputs/Upload.vue
Labels: Change Type | New Feature

#486 [AIDAPP-524]: Fix configuration loading issues while cached
  app-modules/audit/src/Providers/AuditServiceProvider.php
  app-modules/authorization/src/Providers/AuthorizationServiceProvider.php
Labels: Change Type | Bug Fix

#489 [AIDAPP-521]: When using the knowledge base and working with an article, the label on the button reads replicate instead of duplicate after initiating a duplicate action
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
  resources/lang/vendor/filament-actions/en/replicate.php
Labels: Change Type | Bug Fix

#491 [AIDAPP-528]: Introduce purchasing as a navigation group
  app-modules/contract-management/src/Filament/Resources/ContractResource.php
  app-modules/license-management/src/Filament/Resources/ProductResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | New Feature

#487 [AIDAPP-526]: Restrict the visibility of a license record to the creator and assigned party only
  app-modules/license-management/src/Models/ProductLicense.php
  app-modules/license-management/src/Models/Scopes/AuthorizeLicensesScope.php
Labels: Change Type | Documentation
