Repository canyongbs/aidingapp, pull requests merged in 2025-06, with the labels that each got.

#568 [CHORE]: Make sure to fully checkout and upgrade stefanzweifel/git-auto-commit-action
  .github/workflows/ci.yml
Labels: Change Type | Bug Fix

#566 [AIDAPP-598]: Implement on page content for status page
  app-modules/portal/routes/api.php
  app-modules/portal/routes/web.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/ServiceMonitorStatusController.php
  app-modules/portal/tests/Unit/ServiceMonitorStatusApiTest.php
  app-modules/service-management/src/Models/ServiceMonitoringTarget.php
  portals/knowledge-management/src/Components/ServiceMonitorAlert.vue
  portals/knowledge-management/src/Components/ServiceMonitorCard.vue
  portals/knowledge-management/src/Pages/ServiceMonitorStatus.vue
  portals/knowledge-management/src/portal.js
  portals/knowledge-management/tailwind.config.js
Labels: Change Type | Content or Styling Update, Change Type | New Feature

#574 Some users have reported that several information in the client portal incidents report are not displaying properly
  portals/knowledge-management/src/Pages/Incidents.vue
Labels: Change Type | Bug Fix

#571 [AIDAPP-614]: Show checked out and returned assets related to the contact record in the client portal
  _ide_helper_models.php
  app-modules/inventory-management/src/Models/AssetCheckIn.php
  app-modules/inventory-management/src/Models/AssetCheckOut.php
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/AssetManagementPortalController.php
  portals/knowledge-management/src/Pages/Assets.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | New Feature

#577 [AIDAPP-619]: Enhance the display of the GDPR banner on the portal
  resources/views/vendor/cookie-consent/dialog.blade.php
Labels: Change Type | Content or Styling Update

#581 [AIDAPP-620]: Improve accessibility by changing the background color to white, enhancing contrast for the 'Was this content helpful?' container
  portals/knowledge-management/src/Pages/ViewArticle.vue
Labels: Change Type | Content or Styling Update

#584 [Bugfix]: Users not having profile images causes Azure to throw error to Sentry unnecessarily
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
  app-modules/authorization/tests/Feature/Filament/Resources/UserResources/Pages/EditUserTest.php
  composer.lock
Labels: Change Type | Bug Fix

#587 [AIDAPP-625]: Remove all traces of the GraphQL API in preparation for transition to a REST API to assist our customers in providing a more familiar interoperability experience
  .gitignore
  .prettierignore
  .prettierrc.json
  _ide_helper_models.php
  app-modules/alert/graphql/alert.graphql
  app-modules/alert/src/Providers/AlertServiceProvider.php
  app-modules/audit/graphql/audit.graphql
  app-modules/audit/src/Providers/AuditServiceProvider.php
  app-modules/contact/graphql/contact-source.graphql
  app-modules/contact/graphql/contact-status.graphql
  app-modules/contact/graphql/contact.graphql
  app-modules/contact/src/Providers/ContactServiceProvider.php
  app-modules/division/graphql/division.graphql
  app-modules/division/src/Providers/DivisionServiceProvider.php
  app-modules/knowledge-base/graphql/knowledge-base-item.graphql
  app-modules/knowledge-base/src/Providers/KnowledgeBaseServiceProvider.php
  app-modules/notification/src/Providers/NotificationServiceProvider.php
  app-modules/service-management/graphql/service-management.graphql
  app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
  app/Concerns/ImplementsGraphQL.php
  app/Console/Commands/GenerateHelperFiles.php
  app/Console/Commands/PrintApiSchema.php
  app/Console/Commands/ValidateGraphQL.php
  app/GraphQL/Directives/CanUseInQueryDirective.php
  app/GraphQL/Directives/FeatureDirective.php
  app/GraphQL/Directives/MorphToRelationDirective.php
  app/GraphQL/Scalars/EducatableId.php
  app/GraphQL/Scalars/InteractableId.php
  app/GraphQL/Scalars/UUID.php
  app/GraphQL/Scalars/Year.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Definitions/SearchByDirective.php
  app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Types/Condition.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/cors.php
  config/lara-asp-graphql.php
  config/lighthouse.php
  docs/api.md
  graphql/schema.graphql
  graphql/system-user.graphql
  graphql/user.graphql
  package-lock.json
  package.json
  phpstan-baseline.php
  routes/web.php
  spectaql.yml
Labels: Change Type | Dependencies, Change Type | New Feature

#588 [AIDAPP-629]: Store all unmatched inbound emails and text messages
  _ide_helper_models.php
  app-modules/engagement/database/factories/UnmatchedInboundCommunicationFactory.php
  app-modules/engagement/database/migrations/2025_06_24_142144_create_unmatched_inbound_communications_table.php
  app-modules/engagement/database/migrations/2025_06_24_153744_data_activate_unmatch_inbound_communication_feature.php
  app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
  app-modules/engagement/src/Jobs/UnmatchedInboundCommunicationsJob.php
  app-modules/engagement/src/Models/UnmatchedInboundCommunication.php
  app-modules/engagement/tests/Jobs/UnmatchInboundResponseTest.php
  app/Console/Kernel.php
  app/Features/UnMatchInboundCommunicationFeature.php
Labels: Change Type | Documentation, Feature Flag Added

#590 Update roadrunner to 2025.1.2
  Dockerfile
Labels: Change Type | DevOps

#591 [Bugfix]: Restore kb article voter polymorphism
  app-modules/contact/src/Models/Contact.php
  app-modules/integration-aws-ses-event-handling/database/migrations/2025_06_24_152234_create_dynamic_engagement_ses_setting.php
  app-modules/portal/database/factories/KnowledgeBaseArticleVoteFactory.php
  app-modules/portal/database/migrations/2025_05_28_185717_remove_voter_type_column_from_knowledge_base_article_votes_table.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
  app-modules/portal/src/Models/KnowledgeBaseArticleVote.php
Labels: Change Type | Bug Fix

#593 [Bugfix]: Make sure UnmatchedInboundCommunicationsJob is dispatched in correct Tenant context
  app/Console/Kernel.php
Labels: Change Type | Bug Fix

#596 [AIDAPP-626]: Feature Flag Cleanup: MakeContactNotPolymorphicFeature
  app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php
  app-modules/inventory-management/src/Filament/Actions/CheckInAssetHeaderAction.php
  app-modules/inventory-management/src/Filament/Actions/CheckOutAssetHeaderAction.php
  app-modules/inventory-management/src/Models/AssetCheckIn.php
  app-modules/inventory-management/src/Models/AssetCheckOut.php
  app-modules/service-management/src/DataTransferObjects/ServiceRequestDataObject.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php
  app-modules/service-management/src/Models/ServiceRequest.php
  app/Features/MakeContactNotPolymorphicFeature.php
  database/migrations/2025_05_14_221016_data_activate_make_contact_not_polymorphic_feature.php
Labels: Change Type | Feature Cleanup
