Repository canyongbs/aidingapp, pull requests merged in 2025-04, with the labels that each got.

#497 [AIDAPP-518]: Overwrite the migration stub to use the tpetry/laravel-postgresql-enhanced classes
  stubs/migration.create.stub
  stubs/migration.stub
  stubs/migration.update.stub
Labels: Change Type | New Feature

#493 [AIDAPP-530]: Engagements sent to contacts are not using the correct communication settings configuration attached to the division.
  app-modules/engagement/src/Notifications/EngagementNotification.php
  app/Models/User.php
Labels: Change Type | Bug Fix

#499 [AIDAPP-536]: Update Laravel Octane to version 2.8.3
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#490 [AIDAPP-520]: Relocate service request information currently in home after logging in under new "Service" area of the updated navigation
  app-modules/portal/src/DataTransferObjects/ServiceRequestData.php
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/Components/HelpCenter.vue
  portals/knowledge-management/src/Components/Services.vue
  portals/knowledge-management/src/Pages/ViewServiceRequest.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | New Feature

#501 [OLYMPUS-441]: Tiptap merge tags type ahead is currently limited to only 5 items and typeahead search does not seem to be working
  composer.lock
Labels: Change Type | Bug Fix

#500 [AIDAPP-537]: Change PHPStan to Level 6 and create a baseline
  app-modules/engagement/tests/EngagementFile/EngagementFilePruningTest.php
  phpstan-baseline.php
  phpstan.neon.dist
Labels: Change Type | Content or Styling Update

#502 [AIDAPP-537]: Bring the ignore back that we will need for Larastan
  phpstan.neon.dist
Labels: Change Type | New Feature

#503 [AIDAPP-532]: Feature Flag Cleanup: ServiceMonitoring
  app-modules/service-management/src/Filament/Resources/ServiceMonitoringResource.php
  app/Features/ServiceMonitoring.php
  database/migrations/2025_03_19_123622_data_actvate_service_monitoring_feature.php
Labels: Change Type | Feature Cleanup

#504 [AIDAPP-542]: The navigation item in the service management section for monitoring should not be plural
  app-modules/service-management/src/Filament/Resources/ServiceMonitoringResource.php
Labels: Change Type | Bug Fix

#508 [AIDAPP-538]: Disable error report of unmatched ignored errors
  phpstan.neon.dist
Labels: Change Type | Bug Fix

#510 [AIDAPP-546]: Update RoadRunner binary
  Dockerfile
Labels: Change Type | Dependencies

#498 [AIDAPP-527]: Display license information to portal users when there are assigned licenses
  app-modules/license-management/src/Filament/Resources/ProductResource/Pages/ListProducts.php
  app-modules/license-management/src/Models/ProductLicense.php
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/LicenseManagementPortalController.php
  phpstan-baseline.php
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/Pages/Licenses.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | New Feature

#506 [AIDAPP-544]: Introduce a new navigation group called Project Management and relocate Tasks underneath it
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#511 [AIDAPP-547]: Update canyongbs/common to version 1.1.1
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#514 [AIDAPP-549]: Update canyongbs/filament-tiptap-editor to version 1.2.3
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#522 [AIDAPP-560]: Remove the Knowledge Base menu page placeholder in the portal
  app-modules/portal/routes/web.php
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | Feature Cleanup

#526 [AIDAPP-558]: Remove Purchase page
  app-modules/purchasing/src/Filament/Pages/Purchases.php
Labels: Change Type | Feature Cleanup

#525 [AIDAPP-561]: Just like service, incidents in the menu navigation should only show up if you are logged in
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | Bug Fix

#530 [AIDAPP-569] : Update Migration
  database/migrations/2025_04_16_195003_tmp_data_migrate_team_user_id_to_users_table.php
Labels: Change Type | Bug Fix
