Repository canyongbs/aidingapp, pull requests merged in 2025-01, with the labels that each got.

#377 [AIDAPP-400]: Uploading of SVG files when configuring partner branding results in exception being thrown
  app-modules/theme/src/Settings/SettingsProperties/ThemeSettingsProperty.php
  resources/views/vendor/filament-panels/components/logo.blade.php
Labels: Change Type | Bug Fix

#373 [AIDAPP-393]: Extend the front-end display of notification options on service request types
  app-modules/service-management/database/migrations/2024_12_30_091625_add_customers_auditors_managers_fields_in_service_request_types_table.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
  app-modules/service-management/src/Models/ServiceRequestType.php
Labels: Change Type | New Feature

#380 [AIDAPP-401]: Update the label used for People Administration to User Management in the navigation group
  app-modules/authorization/src/Filament/Resources/PermissionResource.php
  app-modules/authorization/src/Filament/Resources/RoleResource.php
  app-modules/division/src/Filament/Resources/DivisionResource.php
  app-modules/team/src/Filament/Resources/TeamResource.php
  app/Filament/Resources/SystemUserResource.php
  app/Filament/Resources/UserResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Documentation

#375 [AIDAPP-394]: Create email templates in the service request types that govern the emails that are sent out for a customer
  app-modules/service-management/database/factories/ServiceRequestTypeEmailTemplateFactory.php
  app-modules/service-management/database/migrations/2024_12_30_090123_create_service_request_type_email_templates_table.php
  app-modules/service-management/database/migrations/2025_01_03_091338_data_activate_service_request_type_email_template_feature.php
  app-modules/service-management/src/Enums/ServiceRequestEmailTemplateType.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
  app-modules/service-management/src/Models/ServiceRequestType.php
  app-modules/service-management/src/Models/ServiceRequestTypeEmailTemplate.php
  app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
  app-modules/service-management/tests/ServiceRequestType/RequestFactories/ServiceRequestTypeEmailTemplateRequestFactory.php
  app-modules/service-management/tests/ServiceRequestType/ServiceRequestTypeEmailTemplatePageTest.php
  app/Features/ServiceRequestTypeEmailTemplateFeature.php
Labels: Change Type | New Feature, Feature Flag Added

#382 [AIDAPP-402]: Feature Flag Cleanup: AzureMatchingPropertyFeature
  app-modules/authorization/database/migrations/2024_12_30_200951_data_activate_azure_matching_property_feature.php
  app-modules/authorization/src/Enums/SocialiteProvider.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app/Features/AzureMatchingPropertyFeature.php
Labels: Change Type | Feature Cleanup

#383 [AIDAPP-413]: Feature Flag Cleanup: ServiceRequestClosedNotificationColumns
  app-modules/service-management/database/migrations/2025_01_03_124223_data_activate_service_request_closed_notification_columns_feature.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
  app/Features/ServiceRequestClosedNotificationColumns.php
Labels: Change Type | Feature Cleanup

#393 [AIDAPP-422]: Introduce bulk service request action to change status
  app-modules/service-management/src/Enums/SystemServiceRequestClassification.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Actions/ChangeServiceRequestStatusBulkAction.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app/Support/BulkProcessingMachine.php
Labels: Change Type | New Feature

#386 [AIDAPP-320]: Add tests for KnowledgeManagementPortalSearchController
  app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest.php
  tests/.pest/snapshots/var/www/html/app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest/categories_and_items_are_returned_without_filtering.snap
  tests/.pest/snapshots/var/www/html/app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest/category_should_present_in_response.snap
  tests/.pest/snapshots/var/www/html/app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest/filter_article_and_category_based_on_searched_keyword.snap
  tests/.pest/snapshots/var/www/html/app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest/filter_article_based_on_selected_tags.snap
  tests/.pest/snapshots/var/www/html/app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest/filter_featured_articles.snap
  tests/.pest/snapshots/var/www/html/app-modules/portal/tests/Unit/KnowlegeManagementPortalSearchTest/filter_most_viewed_articles.snap
Labels: Change Type | New Feature

#389 [AIDAPP-421]: By default, exclude closed service requests via a removable filter from dashboard and service request list views
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
Labels: Change Type | Content or Styling Update

#398 [AIDAPP-430]: Apply the filter to see open service requests to the homepage dashboard
  app/Filament/Widgets/ListServiceRequestTableWidgets.php
Labels: Change Type | New Feature

#397 [AIDAPP-425]: Implement radio button descriptions for assignment types
  app-modules/service-management/src/Enums/ServiceRequestTypeAssignmentTypes.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeAssignments.php
Labels: Change Type | Content or Styling Update

#399 [AIDAPP-431]: Make all columns toggleable (show/hide) except service request # on the home page
  app/Filament/Widgets/ListServiceRequestTableWidgets.php
Labels: Change Type | Content or Styling Update

#387 [AIDAPP-416]: Enhance the service request assignment capabilities
  app-modules/service-management/src/Exceptions/AttemptedToAssignNonManagerToServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php
  app-modules/service-management/src/Observers/ServiceRequestAssignmentObserver.php
  app-modules/service-management/tests/ServiceRequest/AssignedToRelationManagerTest.php
  app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
Labels: Change Type | New Feature

#401 [AIDAPP-161]: Upgrade the core application to run on the latest PHP framework Laravel 11
  app-modules/authorization/composer.json
  app-modules/authorization/database/migrations/2023_07_11_182500_create_permission_tables.php
  app-modules/authorization/src/Models/Concerns/HasRolesWithPivot.php
  app-modules/authorization/src/Models/Role.php
  app-modules/service-management/src/Models/ServiceRequest.php
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
  app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
  app/Exceptions/Handler.php
  app/GraphQL/Directives/MorphToRelationDirective.php
  app/GraphQL/Scalars/UUID.php
  app/Models/HealthCheckResultHistoryItem.php
  app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Definitions/SearchByDirective.php
  app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Types/Condition.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php
  tests/TestCase.php
Labels: Change Type | Dependencies
