Repository canyongbs/aidingapp, pull requests merged in 2025-07, with the labels that each got.

#602 [Bugfix]: Add Checks and refresh for Service Request creation in portal
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
  app-modules/service-management/src/Models/ServiceRequest.php
Labels: Change Type | Bug Fix

#603 [Hotfix]: 0.68.3
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
  app-modules/service-management/src/Models/ServiceRequest.php
Labels: Change Type | Bug Fix

#599 [AIDAPP-637]: Introduce the ability to create a project
  app-modules/project/composer.json
  app-modules/project/database/factories/.gitkeep
  app-modules/project/database/factories/ProjectFactory.php
  app-modules/project/database/migrations/.gitkeep
  app-modules/project/database/migrations/2025_06_30_100112_create_projects_table.php
  app-modules/project/database/migrations/2025_06_30_131142_data_activate_project_feature_flag.php
  app-modules/project/database/seeders/.gitkeep
  app-modules/project/src/Filament/Resources/ProjectResource.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/CreateProject.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/EditProject.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ListProjects.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ViewProject.php
  app-modules/project/src/Models/.gitkeep
  app-modules/project/src/Models/Project.php
  app-modules/project/src/Observers/ProjectObserver.php
  app-modules/project/src/Policies/ProjectPolicy.php
  app-modules/project/src/ProjectPlugin.php
  app-modules/project/src/Providers/ProjectServiceProvider.php
  app-modules/project/tests/.gitkeep
  app-modules/project/tests/Landlord/.gitkeep
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/CreateProjectTest.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/EditProjectTest.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ListProjectsTest.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ViewProjectTest.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/RequestFactory/CreateProjectRequestFactory.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/RequestFactory/EditProjectRequestFactory.php
  app/Features/ProjectFeatureFlag.php
  composer.json
  composer.lock
Labels: Change Type | New Feature, Feature Flag Added

#620 [AIDAPP-657]: Update Olympus API tenant creation to work without a name passed
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
Labels: Change Type | New Feature

#610 [AIDAPP-638]: Introduce the ability to assign teams or users to a project
  app-modules/project/database/migrations/2025_07_03_112418_create_project_manager_users_table.php
  app-modules/project/database/migrations/2025_07_03_112505_create_project_manager_teams_table.php
  app-modules/project/database/migrations/2025_07_03_112607_create_project_auditor_teams_table.php
  app-modules/project/database/migrations/2025_07_03_112629_create_project_auditor_users_table.php
  app-modules/project/database/migrations/2025_07_07_172516_data_activate_project_managers_auditors_feature_feature_flag.php
  app-modules/project/src/Filament/Resources/ProjectResource.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageAuditors.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageManagers.php
  app-modules/project/src/Filament/Resources/ProjectResource/RelationManagers/AuditorTeamsRelationManager.php
  app-modules/project/src/Filament/Resources/ProjectResource/RelationManagers/AuditorUsersRelationManager.php
  app-modules/project/src/Filament/Resources/ProjectResource/RelationManagers/ManagerTeamsRelationManager.php
  app-modules/project/src/Filament/Resources/ProjectResource/RelationManagers/ManagerUsersRelationManager.php
  app-modules/project/src/Models/Project.php
  app-modules/project/src/Models/ProjectAuditorTeam.php
  app-modules/project/src/Models/ProjectAuditorUser.php
  app-modules/project/src/Models/ProjectManagerTeam.php
  app-modules/project/src/Models/ProjectManagerUser.php
  app-modules/project/src/Models/Scopes/ProjectVisibilityScope.php
  app-modules/project/src/Policies/ProjectPolicy.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/EditProjectTest.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ListProjectsTest.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ViewProjectTest.php
  app-modules/team/src/Models/Team.php
  app-modules/team/src/Policies/TeamPolicy.php
  app/Features/ProjectManagersAuditorsFeature.php
  app/Models/User.php
  app/Policies/UserPolicy.php
Labels: Change Type | New Feature, Feature Flag Added

#623 [AIDAPP-649]: Some users are experiencing issues where searching for a service request is not working as expected
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app/Filament/Widgets/ListServiceRequestTableWidgets.php
Labels: Change Type | Bug Fix
