Repository canyongbs/aidingapp, pull requests merged in 2025-02, with the labels that each got.

#396 [AIDAPP-423]: Introduce bulk service request action to add a request update
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Actions/AddServiceRequestUpdateBulkAction.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/tests/ServiceRequest/Actions/AddServiceRequestUpdateBulkActionTest.php
Labels: Change Type | New Feature

#406 [AIDAPP-438]: Enhance the ability to distinguish the main navigation from the page itself
  resources/css/filament/admin/theme.css
Labels: Change Type | Content or Styling Update

#404 [AIDAPP-439]: Improve display of third level navigation throughout the application
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app-modules/audit/src/Filament/Resources/AuditResource.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/AssetManagement.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ContactServiceManagement.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactAlerts.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactEngagement.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactFiles.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactSubscriptions.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactTasks.php
  app-modules/contact/src/Filament/Resources/ContactSourceResource.php
  app-modules/contact/src/Filament/Resources/ContactStatusResource.php
  app-modules/contact/src/Filament/Resources/OrganizationIndustryResource.php
  app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/ManageContacts.php
  app-modules/contact/src/Filament/Resources/OrganizationTypeResource.php
  app-modules/contract-management/src/Filament/Resources/ContractTypeResource.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
  app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php
  app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseQualityResource.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseStatusResource.php
  app-modules/license-management/src/Filament/Resources/ProductResource/Pages/ManageProductLicenses.php
  app-modules/report/src/Filament/Pages/ServiceRequests.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ManageAssignments.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ManageServiceRequestUpdate.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ManageServiceRequestTypeAuditors.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ManageServiceRequestTypeManagers.php
  app-modules/service-management/src/Filament/Resources/SlaResource.php
  app/Filament/Pages/AmazonS3.php
  app/Filament/Resources/NotificationSettingResource.php
  app/Filament/Resources/PronounsResource.php
  app/Filament/Resources/TagResource.php
  resources/css/filament/admin/theme.css
Labels: Change Type | New Feature

#407 [AIDAPP-435]: Update Roadrunner to 2024.3.2
  Dockerfile
Labels: Change Type | Documentation

#403 [AIDAPP-436]: Intermittent error occurs when clicking the "Assign to Me" button in service request assignments
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php
  app-modules/service-management/tests/ServiceRequest/AssignedToRelationManagerTest.php
  app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
  app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
Labels: Change Type | Bug Fix

#411 [AIDAPP-446]: Tickets are failing to automatically assign the designated user on new ticket creation
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php
Labels: Change Type | Bug Fix

#413 [AIDAPP-447]: Add an optional Change Status option to happen simultaneously when creating a service request update
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php
Labels: Change Type | New Feature

#425 [AIDAPP-450]: Add .psysh_history to the .gitignore
  .gitignore
Labels: Change Type | Content or Styling Update

#415 [AIDAPP-458]: Introduce the ability to filter the user list by team
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource.php
Labels: Change Type | New Feature

#417 [AIDAPP-461]: Enhance the user list experience by introducing filters for each license type
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource.php
Labels: Change Type | New Feature

#423 [AIDAPP-452]: Update to RoadRunner v2024.3.4
  Dockerfile
Labels: Change Type | Dependencies

#418 [AIDAPP-451]: Accessing the report library generates an exception
  app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php
  app-modules/report/src/Filament/Widgets/TopServiceRequestTypesTable.php
Labels: Change Type | Bug Fix

#420 [AIDAPP-459]: Introduce new users list view bulk license assign operation
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Actions/AssignLicensesBulkAction.php
Labels: Change Type | New Feature

#426 [AIDAPP-460]: Introduce the ability to assign teams to users in bulk to improve access control management
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Actions/AssignTeamBulkAction.php
  app/Models/User.php
Labels: Change Type | New Feature

#434 [AIDAPP-472]: Feature Flag Cleanup: IncidentSeverityStatus
  app-modules/service-management/database/migrations/2025_02_11_164959_seed_incident_metadata_for_existing_tenants.php
  app-modules/service-management/src/Filament/Resources/IncidentResource.php
  app-modules/service-management/src/Filament/Resources/IncidentSeverityResource.php
  app-modules/service-management/src/Filament/Resources/IncidentStatusResource.php
  app/Features/IncidentSeverityStatus.php
  database/migrations/2025_02_12_111624_data_activate_feature_flag_incident_management.php
Labels: Change Type | Feature Cleanup

#433 [AIDAPP-475]: Add team assignment to the view and edit pages for managing users
  app/Filament/Resources/UserResource.php
  app/Models/User.php
Labels: Change Type | Content or Styling Update

#435 [AIDAPP-476]: Display the relationship a contact has to an organization in the classification section of the record
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/CreateContact.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/EditContact.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ViewContact.php
Labels: Change Type | New Feature

#438 [AIDAPP-454] & [AIDAPP-465]: Enhance permissions with a role matrix editor with bulk selection features and refactor task permissions design to increase efficiency creating and assigning tasks
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php
  app-modules/authorization/src/Filament/Resources/RoleResource.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ViewRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/RelationManagers/PermissionsRelationManager.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
  app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
  app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php
  app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Actions/AddServiceRequestUpdateBulkAction.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Actions/ChangeServiceRequestStatusBulkAction.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
  app-modules/service-management/src/Policies/ServiceRequestPolicy.php
  app-modules/service-management/src/Rules/ManagedServiceRequestType.php
  app-modules/task/src/Observers/TaskObserver.php
  app-modules/task/src/Policies/TaskPolicy.php
  app-modules/task/tests/EditTaskTest.php
  app-modules/task/tests/TaskAssignmentTest.php
  app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
  app-modules/timeline/src/Filament/Pages/TimelinePage.php
  app-modules/webhook/src/Policies/InboundWebhookPolicy.php
  app/Filament/Pages/AmazonS3.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Filament/Pages/ProductHealth.php
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  composer.json
  composer.lock
  database/migrations/2025_02_25_125840_data_normalize_permissions.php
  database/migrations/Concerns/CanModifyPermissions.php
  docker-compose.dev.yml
  routes/web.php
  tailwind.config.js
Labels: Change Type | New Feature

#437 [AIDAPP-441]: Remove Laravel Scout
  .env.example
  .github/workflows/ci.yml
  app-modules/contact/src/Filament/Resources/OrganizationResource/RelationManagers/ContactsRelationManager.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/ListEmailTemplates.php
  app-modules/form/src/Filament/Tables/Filters/FormSubmissionStatusFilter.php
  app-modules/inventory-management/src/Filament/Resources/AssetResource/Pages/ListAssets.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/RelationManagers/SubCategoriesRelationManager.php
  app-modules/service-management/src/Filament/Resources/IncidentResource/Pages/ListIncidents.php
  app-modules/service-management/src/Filament/Resources/IncidentSeverityResource/Pages/ListIncidentSeverities.php
  app-modules/service-management/src/Filament/Resources/IncidentStatusResource/Pages/ListIncidentStatuses.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ManageServiceRequestTypeAuditors.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ManageServiceRequestTypeManagers.php
  app-modules/service-management/src/Filament/Resources/SlaResource/Pages/ListSlas.php
  app/Concerns/FilterTableWithOpenSearch.php
  app/Console/Commands/OpenSearchDeleteAllIndices.php
  app/Console/Commands/OpenSearchList.php
  app/Filament/Resources/NotificationSettingResource/Pages/ListNotificationSettings.php
  app/Filament/Tables/Columns/OpenSearch/Concerns/OpenSearchQueryDefault.php
  app/Filament/Tables/Columns/OpenSearch/OpenSearchColumn.php
  app/Filament/Tables/Columns/OpenSearch/TextColumn.php
  app/Filament/Tables/Filters/OpenSearch/OpenSearchFilter.php
  app/Filament/Tables/Filters/OpenSearch/SelectFilter.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/opensearch.client.php
  config/opensearch.migrations.php
  config/opensearch.scout_driver.php
  config/scout.php
  docs/integrations/opensearch.md
  phpunit-ci.xml
  phpunit.xml
Labels: Change Type | Feature Cleanup

#442 [AIDAPP-479]: Feature Flag Cleanup: DivisionIsDefault
  app-modules/division/src/Filament/Resources/DivisionResource/Pages/CreateDivision.php
  app-modules/division/src/Filament/Resources/DivisionResource/Pages/EditDivision.php
  app-modules/division/src/Filament/Resources/DivisionResource/Pages/ListDivisions.php
  app-modules/division/src/Filament/Resources/DivisionResource/Pages/ViewDivision.php
  app-modules/team/src/Filament/Resources/TeamResource/Pages/CreateTeam.php
  app-modules/team/src/Filament/Resources/TeamResource/Pages/EditTeam.php
  app/Features/DivisionIsDefault.php
  database/migrations/2025_02_19_125556_data_activate_division_is_default_feature_flag.php
Labels: Change Type | Feature Cleanup

#443 [AIDAPP-480]: Update the license in the composer.json
  composer.json
Labels: Change Type | Content or Styling Update

#445 [AIDAPP-485]: Fix path to generated portal and widget css
  portals/knowledge-management/src/App.vue
  widgets/service-request-feedback-form/src/App.vue
  widgets/service-request-form/src/App.vue
Labels: Change Type | Bug Fix

#446 [AIDAPP-485]: Change the vite config to name the stylesheets style.css
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/vite.config.js
  widgets/service-request-feedback-form/src/App.vue
  widgets/service-request-feedback-form/vite.config.js
  widgets/service-request-form/src/App.vue
  widgets/service-request-form/vite.config.js
Labels: Change Type | Bug Fix

#447 [Hotfix]: 0.51.1
  portals/knowledge-management/vite.config.js
  widgets/service-request-feedback-form/vite.config.js
  widgets/service-request-form/vite.config.js
Labels: Change Type | Bug Fix
