Repository canyongbs/aidingapp, pull requests merged in 2025-05, with the labels that each got.

#533 [AIDAPP-567] : Remove Temp Data Migration
  database/migrations/2025_04_16_195003_tmp_data_migrate_team_user_id_to_users_table.php
Labels: Change Type | Feature Cleanup

#534 [AIDAPP-509]: Create a description for each permission group that reflects what capabilities it authorizes
  app-modules/authorization/src/Enums/PermissionDescription.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ViewRole.php
  composer.json
  composer.lock
Labels: Change Type | Content or Styling Update

#537 [Bugfix]: Docker Build Fix
  Dockerfile
  package.json
Labels: Change Type | Bug Fix

#540 [AIDAPP-580]: Remove the PHP package spatie/laravel-ignition
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#539 [AIDAPP-577]: Temporary Data Migration Cleanup: app-modules/service-management/database/migrations/2025_05_03_105320_tmp_data_seed_service_request_type_email_templates.php
  app-modules/service-management/database/migrations/2025_05_03_105320_tmp_data_seed_service_request_type_email_templates.php
Labels: Change Type | Feature Cleanup

#543 [AIDAPP-587]: Feature Flag Cleanup: ServiceRequestTypeEmailTemplateTabs
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
  app/Features/ServiceRequestTypeEmailTemplateTabs.php
  database/migrations/2025_04_22_130524_data_activate_service_request_type_email_template_tabs.php
Labels: Change Type | Feature Cleanup

#545 [AIDAPP-581]: Purge unused permissions
  app-modules/authorization/database/migrations/2025_05_09_171330_purge_unused_permissions.php
Labels: Change Type | Feature Cleanup

#548 [AIDAPP-571]: Implement a new portal navigation page for status
  portals/knowledge-management/src/Components/Header.vue
  portals/knowledge-management/src/portal.js
Labels: Change Type | New Feature

#547 [AIDAPP-586]: Introduce the ability to set a custom label on the button for viewing service requests in the email notification blocks for customers, managers, and auditors
  app-modules/service-management/resources/views/blocks/previews/service-request-link.blade.php
  app-modules/service-management/resources/views/blocks/rendered/service-request-link.blade.php
  app-modules/service-management/src/Filament/Blocks/ServiceRequestTypeEmailTemplateButtonBlock.php
Labels: Change Type | New Feature

#546 [AIDAPP-556]: Scan and improve underlying codebase
  app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
  app-modules/alert/src/Models/Alert.php
  app-modules/alert/src/Notifications/AlertCreatedNotification.php
  app-modules/alert/src/Observers/AlertObserver.php
  app-modules/alert/src/Rules/ConcernIdExistsRule.php
  app-modules/audit/src/Actions/Finders/AuditableModels.php
  app-modules/audit/src/Overrides/Concerns/AttachOverrides.php
  app-modules/audit/src/Settings/AuditSettings.php
  app/Support/FilterQueryBuilder.php
  app/Support/HasAdvancedFilter.php
  app/View/Components/DatePicker.php
  app/View/Components/Dropzone.php
  app/View/Components/SelectList.php
  database/factories/Concerns/RandomizeState.php
  database/factories/EnrollmentFactory.php
  database/factories/ProgramFactory.php
  phpstan-baseline.php
  tests/Helpers/AccessControl.php
  tests/Helpers/Events/EventListener.php
  tests/Pest.php
  tests/TestCase.php
  tests/Unit/ArchTest.php
Labels: Change Type | Content or Styling Update

#550 [AIDAPP-582]: ServiceMonitoringCheckJob fails and throws an error if it's target requires more than 5 redirects
  app-modules/service-management/src/Jobs/ServiceMonitoringCheckJob.php
Labels: Change Type | Bug Fix

#552 [AIDAPP-599]: Some users are reporting that the rich text editor fails to load when editing existing articles in the administrative experience
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#554 [AIDAPP-590]: Feature Flag Cleanup: SurveyResponseTemplate
  app-modules/service-management/database/migrations/2025_05_12_101058_tmp_data_seed_for_survey_response_in_service_request_type_email_templates.php
  app-modules/service-management/resources/views/filament/resources/service-request-type-resource/pages/edit-service-request-type-notifications/matrix.blade.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
  app-modules/service-management/src/Notifications/Concerns/HandlesServiceRequestTemplateContent.php
  app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
  app/Features/SurveyResponseTemplate.php
  database/migrations/2025_05_13_073325_data_activate_feature_flag_survey_response_template.php
Labels: Change Type | Feature Cleanup

#551 [AIDAPP-585]: Purge subscriptions from the product
  _ide_helper_models.php
  app-modules/alert/src/Listeners/NotifySubscribersOfAlertCreated.php
  app-modules/alert/src/Models/Alert.php
  app-modules/alert/src/Notifications/AlertCreatedNotification.php
  app-modules/alert/src/Observers/AlertObserver.php
  app-modules/alert/src/Providers/AlertServiceProvider.php
  app-modules/alert/tests/AlertCreateTest.php
  app-modules/alert/tests/Notifications/AlertCreatedNotificationTest.php
  app-modules/authorization/src/Enums/PermissionDescription.php
  app-modules/contact/src/Filament/Resources/ContactResource.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ListContacts.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactSubscriptions.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ViewContact.php
  app-modules/contact/src/Filament/Widgets/ContactStats.php
  app-modules/contact/src/Models/Contact.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/engagement/src/Models/EngagementFileEntities.php
  app-modules/engagement/src/Observers/EngagementFileEntitiesObserver.php
  app-modules/engagement/src/Observers/EngagementObserver.php
  app-modules/notification/database/factories/SubscriptionFactory.php
  app-modules/notification/database/migrations/2025_05_16_095858_drop_subscriptions_table.php
  app-modules/notification/graphql/subscription.graphql
  app-modules/notification/src/Actions/SubscriptionToggle.php
  app-modules/notification/src/Events/SubscriptionCreated.php
  app-modules/notification/src/Events/TriggeredAutoSubscription.php
  app-modules/notification/src/Exceptions/SubscriptionAlreadyExistsException.php
  app-modules/notification/src/Filament/Actions/SubscribeBulkAction.php
  app-modules/notification/src/Filament/Actions/SubscribeHeaderAction.php
  app-modules/notification/src/Filament/Actions/SubscribeTableAction.php
  app-modules/notification/src/Listeners/CreateAutoSubscription.php
  app-modules/notification/src/Listeners/NotifyUserOfSubscriptionCreated.php
  app-modules/notification/src/Listeners/NotifyUserOfSubscriptionDeleted.php
  app-modules/notification/src/Models/Concerns/HasSubscriptions.php
  app-modules/notification/src/Models/Contracts/CanTriggerAutoSubscription.php
  app-modules/notification/src/Models/Contracts/Subscribable.php
  app-modules/notification/src/Models/Subscription.php
  app-modules/notification/src/Observers/SubscriptionObserver.php
  app-modules/notification/src/Policies/SubscriptionPolicy.php
  app-modules/notification/src/Providers/NotificationServiceProvider.php
  app-modules/notification/src/Rules/SubscribableIdExistsRule.php
  app-modules/notification/src/Rules/UniqueSubscriptionRule.php
  app-modules/service-management/src/Models/ServiceRequest.php
  app-modules/service-management/src/Models/ServiceRequestAssignment.php
  app-modules/service-management/src/Models/ServiceRequestUpdate.php
  app-modules/service-management/src/Observers/ServiceRequestAssignmentObserver.php
  app-modules/service-management/src/Observers/ServiceRequestObserver.php
  app-modules/service-management/src/Observers/ServiceRequestUpdateObserver.php
  app-modules/service-management/tests/ServiceRequestUpdate/CreateServiceRequestUpdateTest.php
  app-modules/task/src/Models/Task.php
  app-modules/task/src/Observers/TaskObserver.php
  app-modules/task/tests/TaskAssignmentTest.php
  app/Filament/Widgets/MyContacts.php
  app/Models/User.php
  database/migrations/2025_05_16_095714_purge_unused_permissions_for_subscriptions.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SuperAdminSeeder.php
  phpstan-baseline.php
Labels: Change Type | Content or Styling Update

#555 [AIDAPP-596]: Enhance the portal by improving the boxed display
  app-modules/portal/resources/views/livewire/render-knowledge-management-portal.blade.php
  portals/knowledge-management/src/Components/Header.vue
Labels: Change Type | Content or Styling Update

#553 [AIDAPP-591]: Scan and improve underlying codebase
  app/Models/Contracts/HasTags.php
  app/Models/NotificationSettingPivot.php
  app/Models/Scopes/EducatableSearch.php
  app/Models/Scopes/EducatableSort.php
  app/Models/Scopes/HasLicense.php
  app/Models/Scopes/LicensedToEducatable.php
  app/Models/Scopes/SearchBy.php
  app/Models/Scopes/SetupIsComplete.php
  app/Models/Scopes/TagsForClass.php
  app/Models/Scopes/TagsForType.php
  app/Models/States/StateMachine.php
  app/Models/SystemUser.php
  app/Models/User.php
  app/Multitenancy/Exceptions/UnableToResolveTenantForEncryptionKey.php
  app/Providers/AuthServiceProvider.php
  app/Providers/MultiConnectionParallelTestingServiceProvider.php
  app/Rules/EmailNotInUseOrSoftDeleted.php
  app/Settings/OlympusSettings.php
  app/Support/BulkProcessingMachine.php
  database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php
  database/migrations/2024_08_01_175631_data_fix_image_ids_in_tiptap_content.php
  phpstan-baseline.php
  tests/Helpers.php
Labels: Change Type | Content or Styling Update

#556 [AIDAPP-589]: Ensure all usage of Cache::tags apply Redis "hash tags" to the tag
  app-modules/alert/src/Observers/AlertObserver.php
  app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactAlerts.php
  app-modules/contact/src/Filament/Widgets/ContactStats.php
  app-modules/contact/src/Observers/ContactObserver.php
  app-modules/report/src/Filament/Widgets/RefreshWidget.php
  app-modules/report/src/Filament/Widgets/ServiceRequestStatusDistributionDonutChart.php
  app-modules/report/src/Filament/Widgets/ServiceRequestsOverTimeLineChart.php
  app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php
  app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/TaskStats.php
  app/Filament/Widgets/ContactGrowthChart.php
Labels: Change Type | Content or Styling Update

#557 [AIDAPP-604]: Update all factories to use the local usage of faker and enforce this as an architecture test
  app-modules/alert/database/factories/AlertFactory.php
  app-modules/authorization/database/factories/PermissionFactory.php
  app-modules/authorization/database/factories/RoleFactory.php
  app-modules/contact/database/factories/ContactFactory.php
  app-modules/contact/database/factories/OrganizationFactory.php
  app-modules/contact/database/factories/OrganizationIndustryFactory.php
  app-modules/contact/database/factories/OrganizationTypeFactory.php
  app-modules/contract-management/database/factories/ContractFactory.php
  app-modules/contract-management/database/factories/ContractTypeFactory.php
  app-modules/division/database/factories/DivisionFactory.php
  app-modules/engagement/database/factories/EmailTemplateFactory.php
  app-modules/engagement/database/factories/EngagementBatchFactory.php
  app-modules/engagement/database/factories/EngagementFactory.php
  app-modules/engagement/database/factories/EngagementResponseFactory.php
  app-modules/inventory-management/database/factories/AssetCheckInFactory.php
  app-modules/inventory-management/database/factories/AssetCheckOutFactory.php
  app-modules/inventory-management/database/factories/AssetFactory.php
  app-modules/inventory-management/database/factories/AssetLocationFactory.php
  app-modules/inventory-management/database/factories/AssetStatusFactory.php
  app-modules/inventory-management/database/factories/AssetTypeFactory.php
  app-modules/inventory-management/database/factories/MaintenanceActivityFactory.php
  app-modules/inventory-management/database/factories/MaintenanceProviderFactory.php
  app-modules/knowledge-base/database/factories/KnowledgeBaseCategoryFactory.php
  app-modules/knowledge-base/database/factories/KnowledgeBaseItemFactory.php
  app-modules/license-management/database/factories/ProductFactory.php
  app-modules/license-management/database/factories/ProductLicenseFactory.php
  app-modules/portal/database/factories/KnowledgeBaseArticleVoteFactory.php
  app-modules/service-management/database/factories/ChangeRequestFactory.php
  app-modules/service-management/database/factories/ChangeRequestStatusFactory.php
  app-modules/service-management/database/factories/ChangeRequestTypeFactory.php
  app-modules/service-management/database/factories/IncidentFactory.php
  app-modules/service-management/database/factories/IncidentSeverityFactory.php
  app-modules/service-management/database/factories/IncidentStatusFactory.php
  app-modules/service-management/database/factories/IncidentUpdateFactory.php
  app-modules/service-management/database/factories/ServiceMonitoringTargetFactory.php
  app-modules/service-management/database/factories/ServiceRequestAssignmentFactory.php
  app-modules/service-management/database/factories/ServiceRequestFactory.php
  app-modules/service-management/database/factories/ServiceRequestTypeEmailTemplateFactory.php
  app-modules/service-management/database/factories/ServiceRequestTypeFactory.php
  app-modules/task/database/factories/TaskFactory.php
  app-modules/team/database/factories/TeamFactory.php
  database/factories/TagFactory.php
  database/factories/UserFactory.php
  tests/Unit/ArchTest.php
Labels: Change Type | New Feature

#560 [AIDAPP-605]: Introduce full text searching from customer portal
  _ide_helper_models.php
  app-modules/knowledge-base/database/migrations/2025_05_23_131036_add_column_article_details_fulltext_in_knowledge_base_articles_table.php
  app-modules/knowledge-base/database/migrations/2025_05_26_103749_data_migrate_article_details_to_article_details_fulltext_in_knowledge_base_articles.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItemMetadata.php
  app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php
  app-modules/knowledge-base/src/Observers/KnowledgeBaseItemObserver.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
  app/Features/ArticleFullTextSearch.php
  database/migrations/2025_05_27_055834_data_activate_article_full_text_search_feature_flag.php
Labels: Change Type | New Feature, Feature Flag Added

#558 [AIDAPP-592]: ServiceMonitoringCheckJob fails if the provided URL is unresolvable
  app-modules/service-management/src/Jobs/ServiceMonitoringCheckJob.php
  app-modules/service-management/tests/Jobs/ServiceMonitoringCheckJobTest.php
Labels: Change Type | Bug Fix
